### ISSUE TITLE
How is the binary release built?

### ISSUE THREAD

**Issue by garywiz** [skavanagh/KeyBox#101]
I confess I am not a Java expert, so I apologize... however, I'm trying to build a leaner Docker image from scratch, and have a great 200MB version using Alpine Linux.  However, if I include Maven and run it using `jetty:run` the image overhead is significant.

What I want to do is:
1.  Build a binary package exactly like your `keybox-jetty-v2.83_02.tar.gz` release, then...
2.  Install the runtime-only build into the leaner JRE environment as I'm doing now.

But, I can't figure out how you built the binary version and can't seem to find the build process anywhere.

If you can point me in the right direction, that would be super helpful, thank you.

**Comment by skavanagh** [comment]
There isn't really a way. It just builds a war file and it should be able to run in any Java EE containers outside of jetty.  (tomcat, liberty, etc..)

**Comment by garywiz** [comment]
Hmm, maybe I'm missing something.   Obviously, the .tar.gz file must be created somehow!  Is it just extracted from the WAR file?  Excuse my Java/Jetty noobieness!

**Comment by skavanagh** [comment]
Yeah I don't have a way to do it.  I just download the latest version of jetty 
http://www.eclipse.org/jetty/
copy some config files over and ssl keys, deploy the war file from the build, and tar it up by hand.

**Comment by garywiz** [comment]
I created a script which (I believe) creates a binary build exactly like the one you've released.    I didn't create a pull request because I found that I got a `NullPointerException` when using the official Jetty 9.2.13 release (the one in your pom.xml file), and had to find a download site for the 9.2.11 version which is the exact version currently in your binary release.  

I did some guessing and would like to know if the script I've created looks correct to you, just in terms of the basic steps I'm going through:

    #!/bin/bash

    # Creates a binary distribution by combining the current KeyBox build with
    # the Jetty distribution.  The results will be in the 'dist' subdirectory.

    cd ${0%/*}

    JETTY_VERSION=9.2.11.v20150529

    JETTY_BASENAME=jetty-distribution-$JETTY_VERSION
    #JETTY_URL=http://download.eclipse.org/jetty/$JETTY_VERSION/dist/$JETTY_BASENAME.tar.gz
    JETTY_URL=https://olex-secure.openlogic.com/content/private/5e6a6f0815e830bba705e79e4a0470fbee8a5880//olex-secure.openlogic.com/jetty-distribution-$JETTY_VERSION.tar.gz

    TARNAME=KeyBox-jetty

    package_dir=$PWD
    dist_dir=$package_dir/dist
    build_dir=$package_dir/dbuild
    keybox_src=$(cd ..; echo $PWD)

    # Copy the source tree into the build directory and create the package locally
    rm -rf $build_dir; mkdir $build_dir
    cp -a $keybox_src/{pom.xml,src} $build_dir

    # Create the Maven package
    cd $build_dir
    mvn package

    # Find the snapshot directory and extract the version number of Keybox
    snapdir=`find $build_dir -type d -name 'keybox-*-SNAPSHOT'`
    [ "$snapdir" == "" ] && (echo "Error: Couldn't find snapshot directory."; exit 1)
    keybox_version=$(echo $snapdir | sed 's^.*/keybox-\([0-9]*\.[0-9]*\)\.\([0-9]*\)-SNAPSHOT^\1_\2^')

    # Get the most recent copy of Jetty
    wget --no-check-certificate $JETTY_URL

    # Now, create the final tar directory by copying in relevant files, with the starter kit as the basis

    rm -rf $TARNAME; mkdir $TARNAME

    # Untar Jetty itself and put it in place
    tar xzf $JETTY_BASENAME.tar.gz
    mv $JETTY_BASENAME $TARNAME/jetty

    # Remove jetty components not needed
    rm -rf $TARNAME/jetty/demo-base

    # Copy keybox into the jetty directory
    mkdir -p $TARNAME/jetty/keybox
    cp -a $snapdir/. $TARNAME/jetty/keybox

    # Add template files
    cp -a ../$TARNAME/. $TARNAME/.

    # Add additional files from the distro
    cp $keybox_src/README.md $keybox_src/LICENSE.md $TARNAME
    cp $keybox_src/src/test/resources/keystore $TARNAME/jetty/etc

    # And create the distribution archive
    mkdir -p $dist_dir
    tarfile=$dist_dir/keybox-jetty-v$keybox_version.tar.gz
    tar czf $tarfile $TARNAME
    echo created $tarfile

    # Remove build directory
    cd $package_dir
    rm -rf $build_dir

The commit in my fork is [located here](https://github.com/garywiz/KeyBox/commit/6892317b09eb5307c63bccd6521db1e6ad8ea62b).

**Comment by skavanagh** [comment]
Great! Thanks Gary. It's a very good start. There would actually have to be a couple of more steps to setup SSL though.  There should be difference in jetty-https.xml, jetty-ssl.xml, and jetty.xml.  Plus the keystore password needs to be set in modules/ssl.mod

**Comment by garywiz** [comment]
Thanks, I'll take a look and diff those files and update it sometime in the next few days.  I've been using KeyBox using our docker image (that I posted about)... in that image, I create a self-signed SSL certificate and a separately managed keystore that goes in persistent storage, so I don't use one in the binary distro.  But, I'm familiar enough with how it works that I think I can update it as you describe.
