### ISSUE TITLE
Suggestion: Mandatory OTP

### ISSUE THREAD

**Issue by garywiz** [skavanagh/KeyBox#102]
We have an environment where we want to guarantee higher security, and would like to see a feature where OTP entry is mandatory.

I couldn't find a way to do this, and I'll fork sometime and add it myself, but it would be a nice configuration option.

+1 for Mandatory OTP.

**Comment by skavanagh** [comment]
+1

**Comment by colandre** [comment]
+1

**Comment by alexolivan** [comment]
On the contrary... I like the freedom of choosing:
It is very annoying the current GUI that is always asking you to setup two factor...
On my early testings I have accidentally not click on skip button: a "one-click away from screwing form" ?!??!!

At our environment we can live with classic login forms... I would like a setup option to completely disable and dismiss OTP

So.... -1

**Comment by garywiz** [comment]
alexolivan... you're missing the point.   

KeyBoxConfig.properties already *has* an option which gives you what you want:

   #enable two-factor authentication
   enableOTP=true

Setting the above to 'false' disables OTP entirely.  Leaving it as 'true' makes it *optional* upon login.  The missing feature is to make it mandatory.

All I asked for, originally, was a way to have three possibilities:
1.  Disabled (now possible)
2.  Optional (now possible)
3.  Mandatory (not possible)

Are you saying that you object to the possibility of making it mandatory, as a configuration option?  If so, why??

**Comment by skavanagh** [comment]
Having a mandatory OTP option would be valuable. It's a little tricky b/c you are logged in when you get to the OTP page. It's definitely doable though.

**Comment by alexolivan** [comment]
aaahhh... ok ok...
I was completely missing it !!!!

+1

**Comment by colandre** [comment]
Hello @skavanagh,

I have tried the mandatory OTP with oneTimePassword=required parameter in KeyBoxConfig.properties file, but I have an issue:

When the user tries to login the first time, the QR Code is displayed correctly and on the right there is only the button "Got it".
After that, the user is redirected to the login page, he/she enter username, password and the OTP, but the QR code and "Got it" button jump out again.
In this way the user is not able to log in.

**Comment by skavanagh** [comment]
Sounds like it's invaliding the session before registering the OTP shared
secret. I'll take a look tonight.

**Comment by colandre** [comment]
I have tested the v2.85.01 and it works correctly.
Thank you for the quick fix.

**Comment by chrisarceo26** [comment]
Same issue. I used google authenticator. When i set the onetimepassword to "enabled" after i clicked "GOT IT" i was not able to log in.

**Comment by skavanagh** [comment]
@chrisarceo26 - I would check the clock on the server that is running KeyBox and make sure NTP is enabled and working.  If the clock is out of sync then the OTP that is generated won't match what the server has.
