### ISSUE TITLE
Prevent accidental window/tab closures

### ISSUE THREAD

**Issue by dnwe** [skavanagh/KeyBox#104]
When using KeyBox I *frequently* accidentally hit Ctrl-W (intending to delete the last word in the terminal) which ends up closing the current tab/window containing my KeyBox terminal(s).

Please could you add a simple JavaScript hook using onbeforeunload to ask for confirmation before closing the tab/window if there are currently some SSH terminals open?

**Comment by skavanagh** [comment]
Unfortunately chrome will close the window before it can be captured - https://code.google.com/p/chromium/issues/detail?id=33056#c12

**Comment by pataquets** [comment]
As a workaround, under Firefox you can disable CTRL+W and many others by using the [Customizable shortcuts extension](https://addons.mozilla.org/ca/firefox/addon/customizable-shortcuts/).
