### ISSUE TITLE
Failing to add systems... No password prompt, Failed status.

### ISSUE THREAD

**Issue by alexolivan** [skavanagh/KeyBox#111]
HI guys...

I'm testing this promising software, it looks incredible!!!...but, unfortunately the show stops very very soon for me: I'm having trouble adding systems to the list.

Out of 5 remote systems, only one, adds.. And not necessary at first attempt.
Of course, I'm able to ssh normally from a terminal console to all systems, but as I add them most of th time I got A "Failed" status and no password is prompt.

I lack a little more documentation on the website.... the feeling is that this project is early at dev stage... Is there a way to run the server in debug mode to see what fails and provide better info on what is failing? I readed about log but I do not find them... Is logging disabled by default?

Bast regards.

**Comment by alexolivan** [comment]
Got it.
It was the password regexp.
We do use secure random passwords, but casually I got '_' char on them, which was missing on the regexp, and looking at our current passwords table I saw some passwds that lack Uppercases... they're random, and only ensure a number and a special char.

So, by now I have disabled Password check by modifying the regexp, so I can use current passwords.
I think this feature should be controllable at the settings tab at some level.

Any how... I think I can add systems.. have to check

**Comment by skavanagh** [comment]
Not quite sure what you mean

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L38

is used to enforce password standards when creating user accounts and  ssh
keys

The password regex isn't used when registering systems.



You can always try and

**Comment by alexolivan** [comment]
hi... hit reality

"The password regex isn't used when registering systems."
you're right it still not work... i cannot add systems.

pd. I was fooled by the fact that my only system that is added to the list has no '_' char at its password... so I wrongly related this with the fact that the '_' char is not among the special chars that keybox considers special in password verification.

**Comment by skavanagh** [comment]
You can always add the public key for keybox manually to the system's authorized_keys file then try and register the system.  

KeyBox-jetty/jetty/keybox/WEB-INF/classes/keydb/id_rsa.pub

**Comment by alexolivan** [comment]
aha.... i see this is more "geeky" than I though.... I heve to try it!

**Comment by alexolivan** [comment]
Aha... I cannot do this...

(check file existence)
# ls /usr/local/KeyBox-jetty/jetty/keybox/WEB-INF/classes/keydb/id_rsa.pub
/usr/local/KeyBox-jetty/jetty/keybox/WEB-INF/classes/keydb/id_rsa.pub

(use ssh-copy-id as usual, but replacing ~/.ssh/idrsa.pub with keybox key)
# ssh-copy-id -i /usr/local/KeyBox-jetty/jetty/keybox/WEB-INF/classes/keydb/id_rsa.pub  admin@someserver
/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/usr/local/KeyBox-jetty/jetty/keybox/WEB-INF/classes/keydb/id_rsa': No such file

...but file exists... So there is something weird here I have to investigate...

**Comment by alexolivan** [comment]
...mmmm KeyBoxConfig.properties suffers automatic rewriting... This has added more confussion to me... : - /

But no change on behaviour... the systems is useless right now.

**Comment by alexolivan** [comment]
got it! ....
This has to do with permissions on the remote authorized_keys or linked (proxmox do use this...) authorized_keys file

by creating a normal, non root user, and ensuring 600 on the authorized_keys systems add...
The strange thing is that I can add the key file using ssh-copy id and ssh normally... so I though everything is usual at server/remote side...
... finally I saw it is different

more testing to com hehehe
