### ISSUE TITLE
Unable to pick host to connect to from drop down list

### ISSUE THREAD

**Issue by splashx** [skavanagh/KeyBox#113]
Browser: Google Chrome 46.0.2490.71 (Official Build) (64-bit) 
OS: OSX 10.11.1 (15B42)

Steps to replicate (make sure you have more than 1 system registered in the "Manage" > "Systems"): 

1. Log into keybox (username, password, OTP)
1. In the upper Menu, select "Secure Shell" > "Composite SSH Terms"
1. Select one machine (any) and "Create SSH Terminal"
1. In the upper menu select "Terminal Actions" > "Connect to Host " - a drop down list will appear

The user is unable to pick a different host than the first one listed (default) - the dropdown menu quickly disappears before the user is able to pick an option.

**Comment by colandre** [comment]
Yes, this happens also to me.

A workaround is to maintain mouse button pressed and move pointer down. After that you are able to select the new system you need to connect to.

**Comment by splashx** [comment]
@colandre thanks for the heads up, however I'd tried that before and that doesn't work for me (I'm however ATM not using a mouse per se but the trackpad @ MacAir).
