### ISSUE TITLE
Issues around KeyBox always writing to the authorized_keys file

### ISSUE THREAD

**Issue by dnwe** [skavanagh/KeyBox#115]
There seem to be a few issues around KeyBox's control of the authorized_keys file.

1)

The documentation seems to suggest that `keyManagementEnabled=false` will disable any key management being performed by Keybox. However, the code would appear to really treat this config setting as "you have total authority over the authorized_keys file" versus "you may only append to this file". The documentation should probably make this clearer.

[SSHUtil.java#L349-L377](https://github.com/skavanagh/KeyBox/blob/61443c88f9c9cedc58839b2d9a80a0d5dec479b7/src/main/java/com/keybox/manage/util/SSHUtil.java#L349-L377)

2)

KeyBox will always rewrite the authorized_keys file even if no change(s) were required. The `ChannelSFTP.put(...)` call is always made at [SSHUtil.java#L376](https://github.com/skavanagh/KeyBox/blob/61443c88f9c9cedc58839b2d9a80a0d5dec479b7/src/main/java/com/keybox/manage/util/SSHUtil.java#L376) regardless of whether any changes were required or not. Ideally the `else { .. } // !keyManagedEnabled` clause should track whether `existingKey` was already present in the file or not and have a `needsWrite=true` boolean so that the file is only written to if an update actually needed to take place.

3)

We've hit a problem where a machine that has 'no space on device' (i.e., zero free space on the mount hosting ~/.ssh) then the content of authorized_keys file will be overwritten with a zero byte file. We believe this is because KeyBox is attempting to write directly to the authorized_keys file. Really, if a write is needed, then it should be creating a temporary file with the new desired content and then if that is successful doing a rename of the temporary file to authorized_keys

**Comment by dnwe** [comment]
as it turns out, every time someone logs on to the machine using keybox, it rewrites the authorized_keys file so to reproduce the 3rd issue we were seeing, all you have to do is attempt to logon to a box with zero free space and it will seemingly corrupt the file

**Comment by skavanagh** [comment]
1. Agree!

2. The reason for this is b/c authorized_keys file could have been changed on the system itself without a public key being registered in KeyBox.  B/c its constantly overwritten it pseudo enforces that public keys have to be registered (and that is why it overwrites it on login too).  But yes probably the better way is to read in the authorized_keys file and determine if it needs updating.

3. That sounds awful and I agree on the fix!

**Comment by skavanagh** [comment]
Modified to 'cat' the authorized_keys and check if it need to be written to

https://github.com/skavanagh/KeyBox/blob/1b31778f05531179a87f631ec6d944b095e74fb7/src/main/java/com/keybox/manage/util/SSHUtil.java#L327

Also, changed to set the keys through the exec channel as well (instead of sftp)
https://github.com/skavanagh/KeyBox/blob/1b31778f05531179a87f631ec6d944b095e74fb7/src/main/java/com/keybox/manage/util/SSHUtil.java#L369

so no more sftp and hopeful zero-byte files when running out of disk

**Comment by dnwe** [comment]
@skavanagh thanks for fixing these :+1: 

do you have any idea of eta when you might cut a new release with these included?

**Comment by skavanagh** [comment]
:ok_hand: I cut a release. You should be set!
