### ISSUE TITLE
Unable to open a terminal if remote host has no sftp subsystem enabled

### ISSUE THREAD

**Issue by dnwe** [skavanagh/KeyBox#116]
Somewhat related to #115 - even if `keyManagementEnabled=false`, KeyBox currently *requires* the sftp subsystem to be enabled on the target host, even though that is not required to bring up a valid SSH terminal. Currently it will fail with `Error: failed to send channel request `  as it tries to open an SFTP channel.

Ideally, disabling the sftp service shouldn't prevent KeyBox from working with the remote host, as it is only required for the current implementation of the key management.

**Comment by skavanagh** [comment]
SFTP is used to upload files too.  JSch doesn't have a channel for scp specifically, but I could maybe try and piggyback off of the exec channel.

**Comment by dnwe** [comment]
I don't think you need worry about working around like that. I was more thinking that if only an exec/shell channel is available then KeyBox should simply fallback to that and disable any key management or file upload capabilities for that host, but it shouldn't prevent you from accessing it at all.
