### ISSUE TITLE
Security problem in profile management.

### ISSUE THREAD

**Issue by Busindre** [skavanagh/KeyBox#118]
Hi!

If a user is created with the profile "All system" (typical mistake) and later that same profile is changed to a more restrictive one, Keybox doesn't change  all the file authorized keys of all the systems. May I suggest this should be corrected?

In my opinion, Keybox should always overwrite the authorized_keys files according to its internal configuration. Keybox users may have ssh keyss that are not in their right place. We also had this problem in the data center.

Thanks!

**Comment by skavanagh** [comment]
+1. Looks like the key is never removed from it's configuration when switching the user type.

**Comment by skavanagh** [comment]
Above should fix the user type issue.  Also, if key management is enabled then the authorized_keys file is overwritten every time a profile is modified, every time someone connects to a system in keybox, and at an interval set here

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L36

That way if someone adds a key manually on the system, it will still overwrite after a set time.
