### ISSUE TITLE
Exception: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by chauffer** [skavanagh/KeyBox#120]
>Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/start/Main : Unsupported major.minor version 52.0
>        at java.lang.ClassLoader.defineClass1(Native Method)
>        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
>        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
>        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
>        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>        at java.security.AccessController.doPrivileged(Native Method)
>        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

-
>java -version
>java version "1.7.0_91"
>OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
>OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)`

Default headless JDK on Ubuntu 14.04 - seems to be an issue on how the release jar is compiled.

**Comment by skavanagh** [comment]
Requires Java JDK 1.8 since v2.84.00
