### ISSUE TITLE
composite terminals not working

### ISSUE THREAD

**Issue by fjoesne** [skavanagh/KeyBox#125]
No error or indication that something is wrong other than that the terminal is not opening.

edit: console tells me the folowing
`irefox can't establish a connection to the server at wss:/`

**Comment by skavanagh** [comment]
This happens when websockets is being blocked.  Are you trying to run it behind a reverse-proxy (nginx or apache)??  This discussion may help https://github.com/skavanagh/KeyBox/issues/51

**Comment by fjoesne** [comment]
Yup, just realized that this was probably the cause. haven’t had time to check it out yet, nginx is most likely the culprit. I'll reopen this if this is not the cause, thanks for your help.
