### ISSUE TITLE
OTP no longer working after moving server

### ISSUE THREAD

**Issue by absane** [skavanagh/KeyBox#127]
I moved the files from the KeyBox folder to a new server and the OTP no longer works. I keep getting authentication errors indicating that my credentials are not correct. I reset the OTP for all the accounts and then retried creating new OTP with Authy but it still does not work.

Since this is a new server I may be missing dependencies besides Java. Could I be missing anything? The only way to authenticate is to disable OTP.

I moved from Ubuntu to Debian.

**Comment by skavanagh** [comment]
The OTP is using a "Time-based One-time Password" so it maybe that the new server's clock is off.  You should make sure the time is synchronized and NTP is enabled and working on the new system.

**Comment by skavanagh** [comment]
Or you could try to create a new "Full Access" user with OTP disabled, then enable OTP, login in with that new user, and then reset all the "Reset OTP Code" for everyone.  I would check the time sync first though!

**Comment by absane** [comment]
NTP... dang I missed that. The clock was off by 145 seconds! Thank you, that solved my problems with migration!

**Comment by skavanagh** [comment]
NP!
