### ISSUE TITLE
How to stop KeyBox?

### ISSUE THREAD

**Issue by darue-keller** [skavanagh/KeyBox#128]
using either kill or even kill -SIGINT result in a exit status of 143.

Is there some way to cleanly shut this down?

**Comment by skavanagh** [comment]
You can run the jetty start/stop script here

 /<whatever directory>/KeyBox-jetty/jetty/bin/jetty start
 /<whatever directory>/KeyBox-jetty/jetty/bin/jetty stop

To set as a daemon/service you should just be able to follow the quick start instructions...

http://www.eclipse.org/jetty/documentation/current/startup-unix-service.html

your JETTY_HOME would need to be set to /<whatever directory>/KeyBox-jetty/jetty

**Comment by darue-keller** [comment]
well, I don't think I'm going to use that jetty.sh script in jetty/bin
I've got this systemd service unit file setup...
`cat /etc/systemd/system/keybox.service
[Unit]
Description=systemd based control of KeyBox
Before=shutdown.target
After=local-fs.target network-online.target
Wants=network-online.target
Conflicts=shutdown.target

[Install]
WantedBy=multi-user.target

[Service]
Type=forking
User=keybox
PIDFile=/opt/KeyBox/keybox.pid
TimeoutStartSec=15
TimeoutStopSec=15
Restart=no
WorkingDirectory=/opt/KeyBox/jetty
UMask=0007
ProtectSystem=full
ProtectHome=yes
ExecStart=/opt/KeyBox/startKeyBox.sh
ExecStop=/bin/kill -SIGHUP $MAINPID`

and I've modified startKeyBox.sh to be like this...

`cat startKeyBox.sh
#!/bin/bash
cd /opt/KeyBox/jetty;
export JAVA_HOME="/opt/JRE"
export PATH="${PATH}:${JAVA_HOME}/bin"
java -Xms1024m -Xmx1024m -jar start.jar &
JAVAPID="$!"
echo "${JAVAPID}">/opt/KeyBox/keybox.pid
exit 0`

This all seems to work well. I switched to SIGHUP to kill with, it does seem clean-er, but jetty still exits with a status of 129, not 0. IIRC, a process that dies due to a signal gets 128 added to it's exit code. I looks around and everything I see says the code running in jetty has to handle exiting as there is no universal way to stop jetty. Maybe the code could just trap SIGHUP and exit cleanly? Maybe it's trying to as with SIGHUP I see this lines in syslog...
`: 2016-03-02 17:18:25.306:INFO:oejs.ServerConnector:Thread-0: Stopped ServerConnector@40ae800a{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
: 2016-03-02 17:18:25.313:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@5034c75a{/,null,UNAVAILABLE}{/opt/KeyBox-jetty-2.85.01/jetty/keybox}
: keybox.service: Main process exited, code=exited, status=129/n/a`

So it looks like some internal bits are shutting themselves down.

Not sure if this even matters, but I get a bit worried about the DB no closing cleanly, but maybe it's perfectly safe to just be killing jetty.
