### ISSUE TITLE
Adding an SSL certificate.

### ISSUE THREAD

**Issue by jskilton** [skavanagh/KeyBox#130]
We really struggled getting SSL cert so that we could browse to our keybox install via HTTPS. We are trying to follow the posts, but there seems to be various versions of Jetty and slight differences between all the documentation out there. IMO if you have the time, including a guide and set of documentation in your docs on how to add an SSL certificate would be most helpful. 

We have tried to follow these guides
http://www.eclipse.org/jetty/documentation/current/configuring-ssl.html
http://www.eclipse.org/jetty/documentation/current/configuring-security-secure-passwords.html

But we seem to be getting errors and issues no matter what we do. Do we have to update / put values in the .INI file?   Do we have to touch or alter the jetty-ssl.xml file? 

We just can't seem to make this work.

**Comment by skavanagh** [comment]
So KeyBox should be able to run in a number of Java EE servers and I don't really want to get in the business of how to setup SSL for a particular server. 

As for jetty is what I do

in jetty/etc/ delete keystore

then either generate a self-signed cert and create a keystore
```
keytool -keystore keystore -alias jetty -genkey -keyalg RSA -sigalg SHA256withRSA
```
or import a cert and create a keystore
```
keytool -import -alias jetty -file mycert.crt -keystore keystore
```
then configure jetty to use the keystore password and do
```
 java -cp jetty/lib/jetty-util-<whatever version>.jar org.eclipse.jetty.util.security.Password <keystore password>
```
the take the OBF value and set it do the default value the jetty/etc/jetty-ssl-context.xml
```
KeyStorePassword
KeyManagerPassword
TrustStorePassword
```
and then I also set the same values in the jetty/modules/ssl.mod for

```
## Keystore password
jetty.sslContext.keyStorePassword=

## KeyManager password
jetty.sslContext.keyManagerPassword=

## Truststore password
jetty.sslContext.trustStorePassword=
```
This should also help - https://github.com/skavanagh/KeyBox/issues/129#issuecomment-191972120

**Comment by TheGrandPackard** [comment]
I wasn't able to add my own certificate with your instructions, @skavanagh. They seemed to be the right commands but all I got was SSL handshake errors. I wrote up a guide on how to add a non self-signed certficate (it worked for my Let's Encrypt certificate) and here's a link to it for anyone still having trouble with adding an SSL certificate:

https://docs.google.com/document/d/16FuDxxYigRkZsX3aLl0ImgQtsnEXPhNfvaQctH_sWgE/edit

**Comment by Busindre** [comment]
Hope this helps!

https://github.com/Busindre/How-to-Change-the-https-certificate-in-KeyBox

Regards

**Comment by skavanagh** [comment]
@Busindre Great - Thanks!

**Comment by neilwhitespace** [comment]
> Hope this helps!
> 
> https://github.com/Busindre/How-to-Change-the-https-certificate-in-KeyBox
> 
> Regards

Thanks for that @Busindre - It was a huge help and so far, the only thing that worked for us!
