### ISSUE TITLE
Allow adding server (system) using SSH key

### ISSUE THREAD

**Issue by mrjk05** [skavanagh/KeyBox#131]
Currently to add a server you need to the username and password plus all the other good stuff (hostname etc)

However I am using AWS and use SSH keypairs to log into my EC2 instances. It would be good to have the option to ignore password and instead connect via SSH keypair

**Comment by skavanagh** [comment]
so the public key that KeyBox generates can be added to EC2. (jetty/keybox/WEB-INF/classes/keydb/id_rsa.pub).  

or you can use one of your EC2 keys and set a custom SSH key for KeyBox to use
https://github.com/skavanagh/KeyBox#supplying-a-custom-ssh-key-pair

Also, there is the is project too.
https://github.com/skavanagh/EC2Box

**Comment by robertoamoreno** [comment]
Is it possible to add multiple public keys, using supplying-a-custom-ssh-key-pair option.

**Comment by skavanagh** [comment]
No it's not, it just uses the one.  You can manage keys inside the app to add additional keys.
