### ISSUE TITLE
Doesn't distribute user's keys correctly.

### ISSUE THREAD

**Issue by daleus** [skavanagh/KeyBox#133]
Hi, this may be me misunderstanding the following two options:
keyManagementEnabled=false
forceUserKeyGeneration=false

I enable these, add some users, add some hosts, create a profile add all to it.

I then get my users to login and add their public SSH keys, however keybox only sends the 'global' keybox key and never their keys they have uploaded. I have checked the resync button and I have also reduced the time between key distribution just incase with no joy.

ps/ I do not want to use generated keys, I wish for users to specify their own - gitlab style.

Cheers!

**Comment by skavanagh** [comment]
Something isn't setup correctly... make sure the profile has both the user and systems assigned to it.  

Users can set the public key "gitlab style", by keeping 'forceUserKeyGeneration' set to 'false'

Hope this helps!

**Comment by daleus** [comment]
As suspected, it was a misunderstanding of my options.

Correct options:
keyManagementEnabled=true
forceUserKeyGeneration=false

This now delivers the correct keys. Issue closed. Thanks Sean.
