### ISSUE TITLE
Openstack

### ISSUE THREAD

**Issue by georgekarl** [skavanagh/KeyBox#134]
I am trying to get Keybox to work with an Openstack cloud provider where I am given a private key based on my security profile. I have tried to set the ssh key name in the config but it is not getting recongized. Is there a way to create a key within Keybox with the public/private key information? Similar to the way you can setup keys in EC2Box? I am new at this and I am struggling.

Thanks !!!

**Comment by skavanagh** [comment]
You can register a private key like so

https://github.com/skavanagh/KeyBox#supplying-a-custom-ssh-key-pair

Once keybox starts up the private key is registered in it's database, the passphrase and the key paths will be removed from the configuration file, and the private key can be removed from the system.
