### ISSUE TITLE
Error After Upgrading to 2.85.03

### ISSUE THREAD

**Issue by alloylab** [skavanagh/KeyBox#137]
Getting this error now, 

/ ---> o.e.j.w.WebAppContext@735b5592{/,file:///opt/KeyBox-jetty/jetty/keybox/,UNAVAILABLE}{/opt/KeyBox-jetty/jetty/keybox} [failed]

upgraded from 2.85.01 to 2.85.03

**Comment by skavanagh** [comment]
Is there more to the error message?? Make sure nothing else is running on the same port.

**Comment by alloylab** [comment]
The error message is displayed in the browser, 

Error 404 - Not Found.

No context on this server matched or handled this request.
Contexts known to this server are:
/ ---> o.e.j.w.WebAppContext@735b5592{/,file:///opt/KeyBox-jetty/jetty/keybox/,UNAVAILABLE}{/opt/KeyBox-jetty/jetty/keybox} [failed]
 Powered by Jetty:// 9.3.8.v20160314

**Comment by skavanagh** [comment]
Ok - had someone else see this too. Add this to your KeyBoxConfig.properties

#H2 DB and Connection Pool settings
#Path to the H2 DB file. Leave Blank to use default location which is ../WEB-INF/classes/keydb
dbPath=
#Max connections in the connection pool
maxActive=25
#When true, objects will be validated before being returned by the connection pool
testOnBorrow=true
#The minimum number of objects allowed in the connection pool before spawning new ones
minIdle=2
#The maximum amount of time (in milliseconds) to block before throwing an exception when the connection pool is exhausted
maxWait=15000

Here is the diff - https://github.com/skavanagh/KeyBox/commit/7357b5a85e5e29b0b3fc73fbc9cda5978961376d#diff-492f27a5044cce8470c2303ab98a06f5L41

I'll add to the release notes

**Comment by alloylab** [comment]
That fixed it! Thanks @skavanagh !
