### ISSUE TITLE
Manage SSH Keys (full access only)

### ISSUE THREAD

**Issue by eduardogsilva** [skavanagh/KeyBox#138]
Maybe I'm missing something, but I just can't find an option to only allow "full access" users to manage ssh keys. 

The idea is to enforce the web interface usage to enable auditing.

Any option to disable it?

Thanks!

**Comment by skavanagh** [comment]
"Full access" users can add "administrative only" users, create profiles, assign systems and users to profiles.  "Administrative only" users can their own ssh key based on the profiles they have assigned.  "Full access" users can disable any key that any users has added.  They can also add their own keys to all systems or any systems under a profile.
