### ISSUE TITLE
Asking for OTP Access code for the first time login

### ISSUE THREAD

**Issue by sudhanva04** [skavanagh/KeyBox#140]
I am trying to setup keybox for the first time and I am supposed to change password by logging in as "admin" with password "changeme". but it is prompting for OTP Acess code.

Thanks in advance:)

![keybox](https://cloud.githubusercontent.com/assets/17919804/16037750/91bcbe08-323f-11e6-834b-568721d5ddf9.jpg)

**Comment by xchz** [comment]
input six number
