### ISSUE TITLE
KeyBox console asking for Kerberos username / password for Solaris targets

### ISSUE THREAD

**Issue by cswiger** [skavanagh/KeyBox#141]
Hi - we have KeyBox running and love it, hits all our RHEL6 boxes just fine. 

I'm trying to setup a Solaris 10 system, and it mostly works - just when starting a composite SSH term we get these on the terminal running ./startKeyBox.sh:

Kerberos username [root]:
Kerberos password for root:

and there it hangs until someone hits "enter" twice then the user can access a terminal just fine. 

We have nothing configured for external authentication in jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties:
#specify a external authentication module (ex: ldap-ol, ldap-ad).  Edit the jaas.conf to set connection details
jaasModule=

and have tried turning off "GSSAPIAuthentication no" in /etc/ssh/ssh_config to no avail.  

Sorry I'm not a Java / Jetty expert, just a happy KeyBox user trying to add a Solaris host!
Thanks!

**Comment by cswiger** [comment]
Have also moved jetty/etc/krb5.ini out of the directory and get the same prompt for Kerberos credentials.

**Comment by skavanagh** [comment]
Are you using a version older than v2.85.02?

I think this should have taken 'gssapi-with-mic' out of the preferred authentication. https://github.com/skavanagh/KeyBox/commit/6e06a1a4e836fec463b40011c893b7b4de58b4dc

as per http://stackoverflow.com/a/29692245

**Comment by cswiger** [comment]
Thanks - updated to 2.85.03 and the problem went away.

**Comment by skavanagh** [comment]
No problem! Thanks @cswiger!
