### ISSUE TITLE
Mysterious authorized_keys behaviour

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [skavanagh/KeyBox#150]
Hi there,

I don´t know if I´m wrong, but there are some questions concerning SSH KeyBox:

1. I´ve done the following settings:

#set to false to disable key management. If false, the KeyBox public key will be appended to the authorized_keys file (instead of it being overwritten completely).
keyManagementEnabled=true
#set to true to generate keys when added/managed by users and enforce strong passphrases set to false to allow users to set their own public key
forceUserKeyGeneration=false

So if I´m right, that means: SSH KeyBox manages the authorized_keys file, users will be able to set their own (maybe already used) public key.

2. I´ve added systems to SSH KeyBox and configure users and profiles. When I added the first system and user to a profile, the users public key was added to the authorized_keys file. So
in the authorized_keys file were the following public keys:

	* key box public key
	* user´s public key

But then I added the second system, added the user to the corresponding profile and the user´s public key wasn´t appended.

I want to achieve the following:

I add the users (public key) to a profile and they will be appended to the authorized_keys file, this is necessary because we need to connect via software like sequel pro, so the users public key has
to be in the authorized_keys file. 

Can someone explain this behavior? It´s quite irritating, that at first the users public key was appended and then not.

**Comment by skavanagh** [comment]
That shouldn't be happening.  Make sure both the user has been added to the profile, the system have been added to the profile, and the key is setup under the profile.

Most of the time the update should be instantaneous, but there are ways where it may take some time for the authorized_keys file to update. A refresh interval is set here.

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L33-L34

**Comment by Pupp3tm4st3r** [comment]
Hi Sean,

user and system are both added to the profile, key is setup.
Just installed a new server, added the system (was the keybox system), added the user. After I manually created the authorized_keys file, ssh keybox added both keys (the "host" key and my key). When I removed the user from the profile, the key was removed, too. But after adding the user once again, no key was added...

I think I found the solution: When removing the user from a group, the key of the user gets removed, too. Is this common behaviour? So I always have to readd the key or make a profile for "all" users...

Regards
Simon

**Comment by Pupp3tm4st3r** [comment]
Okay, now I´m even more irritated:

When adding my own key as a normal user, I have to chose for what profile. So this means: We have about 50 systems - I have to add 50! keys? I can only chose one profile per key...

**Comment by skavanagh** [comment]
Keys aren't kept around. If a user is removed from a profile, then the key is removed.  If they are added back to a profile, then they have to set their key up again.  "Managers" can add keys to all systems, but there is nothing stopping you from having an all systems profile and adding all 50 systems to it for regular users.

**Comment by Pupp3tm4st3r** [comment]
Mhm, yeah thought of that, too. Creates a bit of an overhead but maybe I have to do it like that..
