### ISSUE TITLE
Problem when using Ctrl+c Key to cancel ongoing operation.

### ISSUE THREAD

**Issue by bhalgatsaket** [skavanagh/KeyBox#151]
If we try to cat any large file and if we want to get out of this to normal prompt we normally press Ctrl+C. This doesn't work in console. The terminal finiishes cat command first and then runs Ctrl+C.

**Comment by skavanagh** [comment]
It's b/c the output isn't able to be processed as fast coming up through the server, through the web socket connection, and to the client. It actually gets there, but the server is playing catch-up to what happened on the ssh session side.
