### ISSUE TITLE
External Authentication ( with AD ) : If password contains international character authentication fails.

### ISSUE THREAD

**Issue by bhalgatsaket** [skavanagh/KeyBox#152]
If we are using External Authentication ( with AD ) some of users has international character like é in the password then authentication fails. We see below error in traces,

_[WARNING] org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! incomplete UTF8 sequence
[LdapLoginModule] search-first mode; SSL disabled
[LdapLoginModule] attempting to authenticate user: XYZ
 [LdapLoginModule] authentication failed
[LdapLoginModule] aborted authentication_

**Comment by skavanagh** [comment]
The first warning is coming from jetty.  I think you could try and add these options to the startKeyBox.sh 

-Dorg.eclipse.jetty.util.URI.charset=ISO-8859-15

-Dorg.eclipse.jetty.util.UrlEncoding.charset=ISO-8859-15

**Comment by bhalgatsaket** [comment]
Thanks for your reply. This has solved the issue.
