### ISSUE TITLE
Whitepaper Link in README 404 Error

### ISSUE THREAD

**Issue by jnaulty** [skavanagh/KeyBox#153]
The Link http://www.sans.org/reading-room/whitepapers/vpns/security-implications-ssh-1180
does not yield a whitepaper. I am interested in reading this, is there any chance you have a copy?

**Comment by skavanagh** [comment]
Looks like the SANS site is having issues.  I can get to a cached verison https://webcache.googleusercontent.com/search?q=cache:DGFJHL3DCtoJ:https://www.sans.org/reading-room/whitepapers/vpns/security-implications-ssh-1180+&cd=1&hl=en&ct=clnk&gl=us

**Comment by skavanagh** [comment]
Looks like the link is working now.
