### ISSUE TITLE
Help me understand forceUserKeyGeneration

### ISSUE THREAD

**Issue by zlanich** [skavanagh/KeyBox#155]
Currently, I have KeyBox set up to have forceUserKeyGeneration=false so users can upload their own ssh key. At first, this seemed easier as some less experienced users don't understand how to use an ssh config file or that you can specify a private key using the ssh CLI command, and it's easier in general for them to just reuse the key they've already generated for many other things. However, after getting into configuration, I realized that every user had to assign essentially the same public key to every single Profile separately, which in practice was very confusing and time consuming as we have multiple profiles. So I have some questions to help me better understand the intentions behind the ways KeyBox handles ssh keys:

- Am I missing something, or is it necessary to assign the same key separately to every profile?
- If I enable forceUserKeyGeneration, does KeyBox generate one key pair for that user to use for every Profile?
-- And does it automatically assign that generated key to all that user's assigned Profiles, or will it make them configure those manually too?
-- And if we have many systems that are on different host names or even just different IPs with no host names attached, how would a user configure an ssh config file to know which key to use automatically so they don't have to manually provide the path to the appropriate private key in the CLI?

On a slightly different note, I have another question:
- Is there any API for connecting external systems so when new servers are created by our automated provisioning system, Profiles, Systems & User Assignments can be automatically added in KeyBox programmatically rather than having to add every new system in by hand?

I hugely appreciate anyone's time in answering my questions as I love KeyBox so far and don't see many options out there like this, and I'd love to continue using it and allow it to grow with our server setup :)

**Comment by skavanagh** [comment]
>Am I missing something, or is it necessary to assign the same key separately to every profile?

Yes keys are associated by profile, you can add the same public key (obviously)

>If I enable forceUserKeyGeneration, does KeyBox generate one key pair for that user to use for every Profile? 

No.  Users request a key be generated for a particular profile (or they can pick from existing keys).  Users download the private key and KeyBox associated the public with the profile. Keys are still associated per profile.

>And if we have many systems that are on different host names or even just different IPs with no host names attached, how would a user configure an ssh config file to know which key to use automatically so they don't have to manually provide the path to the appropriate private key in the CLI?

Users need to keep track of which systems the private key is for.  A lot of that can depend on how the profiles are setup and users can use the same public key for multiple profiles.

>Is there any API for connecting external systems so when new servers are created by our automated provisioning system, Profiles, Systems & User Assignments can be automatically added in KeyBox programmatically rather than having to add every new system in by hand?  

No there isn't. You could add to the H2 database directly or if you are using EC2 there is https://github.com/skavanagh/EC2Box

**Comment by zlanich** [comment]
How would "users use the same public key for multiple profiles" When forceUserKeyGeneration=true if it generates a separate key for every Profile? I may just have misunderstood your answer.

**Comment by skavanagh** [comment]
There is a way to create the key based on existing keys that have been generated for other profiles.  But the key would still need to be removed per profile. ![gen-keys](https://cloud.githubusercontent.com/assets/3192731/17059298/7cd161f8-4ff2-11e6-8d13-73994014f854.png)

**Comment by zlanich** [comment]
So, that screenshot is the interface when key generation is on? I know that's what the screen looks like when it is off.

**Comment by zlanich** [comment]
Ok, that's cool. I'll check it out. One more question (and I really appreciate your time btw):

When you say "You could add to the H2 database directly", can you provide a bit of an explanation that would point me in the right direction for what I would need to do that? I know this app runs on Java, and I'm not a well-versed Java Developer, but if I have some direction, I can figure it out.

Thanks again!

**Comment by skavanagh** [comment]
it runs an embedded database and you can download the client here.
http://www.h2database.com/html/main.html
the connection info is in the DSPool class

**Comment by zlanich** [comment]
That's exactly what I needed. Thank you so much.

**Comment by dematic-jason-deland** [comment]
Could we create a REST service that just calls insertSystem from keybox/manage/db/SystemDB.java?

**Comment by zlanich** [comment]
This would be incredible if you did. If knew a lick of Java, I’d help :/

Best Regards,

Zach Lanich
Business Owner, Entrepreneur, Creative
Owner/CTO
weCreate LLC
www.WeCreate.com

**Comment by pratibhadeepti** [comment]
hi can you explain me how can I add ec2 ubuntu or rhel server, do I need to create separate user with password as aws doesnot provide any default password for root so how can I connect.
