### ISSUE TITLE
add servers to the server pool without web interface

### ISSUE THREAD

**Issue by nickmisasi13** [skavanagh/KeyBox#156]
Is there any way/any way planned to automatically add servers to the system list? 

I manage a large pool of VM's that are constantly created and deleted and would like the ability to have a script automatically add a server to the list when it's created so that I don't have to manually do it. Any plans for a REST API or CLI?

**Comment by skavanagh** [comment]
No there isn't an API (maybe sometime in the future). It's possible to add to the H2 DB directly and maybe the VM could be created with public key for KeyBox.  There is some discussion here on how to do that https://github.com/skavanagh/KeyBox/issues/155#issuecomment-234647145

**Comment by nickmisasi13** [comment]
Hi, 

I've gone the route of adding to the database directly, but have hit a snag, and figured you may know how to help since you're probably more experienced with the architecture. 

I am able to query the database directly - only when the keybox service isn't running. If it is, the query returns an error `SQL Exceptionorg.h2.jdbc.JdbcSQLException: Database may be already in use: "<db location>". Possible solutions: close all other connection(s); use the server mode [90020-192]`

Trying to connect to the database through tcp over localhost causes a connection refused, so I'm assuming that the database isn't launched in server mode by keybox. Would you happen to know where I can find the database settings so that I can connect multiple connections at once? Or do you have any other suggestions?

**Comment by skavanagh** [comment]
It's probably b/c keybox is running, since H2 is embedded it's only
allowing for one connection.  You can shutdown keybox or you can change H2
connection string

https://github.com/skavanagh/KeyBox/blob/master/src/main/java/com/keybox/manage/util/DSPool.java#L72

to use mixed mode

http://www.h2database.com/html/features.html#auto_mixed_mode

**Comment by nickmisasi13** [comment]
Awesome. I figured it was that but I was trying to use "localhost" instead of imbedded in "application 2"

What however, Doing this causes an "encryption error in file .../keybox.h2.db" which has stumped me pretty hard

**Comment by skavanagh** [comment]
Are you using the shell tool?

java -cp <path_to_h2>/h2.jar org.h2.tools.Shell -url
"jdbc:h2:file:<jdbc_url>" -driver "org.h2.Driver" -user "" -password ""

You need to pass in the credentials (user and password flag) that are
in the DSPool class.
