### ISSUE TITLE
Add support for Netflix/bless 

### ISSUE THREAD

**Issue by adilr00t** [skavanagh/KeyBox#157]
Is it possible to add support for https://github.com/Netflix/bless

https://www.youtube.com/watch?v=JwLGsWYVjqU

**Comment by adilr00t** [comment]
@skavanagh or you think the issue is to be moved to https://github.com/skavanagh/EC2Box

**Comment by skavanagh** [comment]
Not sure how it would fit in, looks like it's using certificate authentication.  In a lot of ways it's better (makes revocation easier), but with more setup.
