### ISSUE TITLE
RedHat / CentOS support

### ISSUE THREAD

**Issue by s3cur3n3t** [skavanagh/KeyBox#158]
Hi guys,

I stumbled upon your product, and I find it really useful, and it's just what we are needing right now for our enterprise, and I would like to know if it supports Red Hat based Linux, cause I see the package says *jetty* a normally it's for a debian distribution..

If not when are you able to support Red Hat based on premises?

Thank you in advance.

S3cur3n3t
"Security is what you make of it!!!"

**Comment by colandre** [comment]
Hello @s3cur3n3t ,

I'm currently running KeyBox on CentOS Linux release 7.1.1503 (Core) without any problem.

**Comment by s3cur3n3t** [comment]
Hello @colandre 

Ok perfect.. That was all I had to know!!! ;)

Thanks
