### ISSUE TITLE
Base URL with long path through reverse proxy

### ISSUE THREAD

**Issue by lioneldeglise** [skavanagh/KeyBox#162]
Hi,

I plan to use Keybox (awesome piece of software, thnak you) through a reverse HAPROXY using an URL like this : https://www.mydomain.com/ssh/.

My temptatives were unsuccessful because browser came back to https://www.mydomain.com/login.action. Is it possible to configure the base URL ? I run a docker image adito/keybox on top of ubuntu 14.04.

Thank by advance

**Comment by skavanagh** [comment]
This should work.  Did you try changing the jetty/webapps/keybox.xml and setting the contextPath from
`<Set name="contextPath">/</Set>`
to
`<Set name="contextPath">/ssh</Set>`
??

**Comment by lioneldeglise** [comment]
Thanks, perfect hint. It works fine.
