### ISSUE TITLE
Accessing Keybox on port 80 weird behaviour

### ISSUE THREAD

**Issue by nickmisasi13** [skavanagh/KeyBox#163]
Hi, I'm compiling KeyBox from source. When changing the settings in jetty-https.xml and jetty.xml from port 8443 to port 80 something weird happens. When navigating to https://keybox-server-here/ the browser immediately just downloads a file called "download" . It can't be opened by anything I've tried, even  a text editor.
![image](https://cloud.githubusercontent.com/assets/12176405/17602249/ce76d744-5fd9-11e6-96b6-e0ee16fdffe2.png)
That's from chrome. Is there something I'm missing? I couldn't find any reference to port 8443 anywhere else in the src.

**Comment by skavanagh** [comment]
change 80 to 443 and then go https://keybox-server-here/ . The standard port for SSL is 443, not 80
