### ISSUE TITLE
What's the scoop with working in openshift?

### ISSUE THREAD

**Issue by waynepennington** [skavanagh/KeyBox#164]
Uhg.

**Comment by skavanagh** [comment]
It's in this repo! https://github.com/skavanagh/KeyBox-OpenShift

**Comment by waynepennington** [comment]
Must be me.  I'll try again.

**Comment by waynepennington** [comment]
I've re-installed three times.  I think it is me or my setup.  I get a successful install via rhc ssh.  Zero errors. Everything looks fine.  However it's keeps giving me a blank response.  I've tried to force particular jsp's.  Nothing.  I've searched stackoverflow and didn't find people with similar issues.  Odd.  It's probably the simplist of things.  But yet, I feel like a moron.

**Comment by waynepennington** [comment]
BTW, if I get this working.  I was thinking, a cool port of your application to a single page app would be nice.  I'm working with Aurelia on the font end.  It's bleeding edge but clean ... but still maybe too forward leaning.

**Comment by skavanagh** [comment]
Looks like it's running out of memory. A larger gear should work (try setting it to medium)
```
rhc app create <app name> jbossews-2.0 --from-code git://github.com/skavanagh/KeyBox-OpenShift.git --gear-size medium
```
you could also try and set the JVM memory like so

https://developers.openshift.com/servers/tomcat/jvm-memory.html

and restart

**Comment by waynepennington** [comment]
Thanks.   I'm looking at moving things to Wildfly-Swarm to get rid of lots of unused baggage.

**Comment by waynepennington** [comment]
'Been a freebee user at Openshift to figure out red hat technologies.  At your advice, I'm upgrading ... trying to.  I must be really bad.  I can't even get my credit card payment setup.  'Sucking wind here.  I'll let you know later how things progress.  That is to say I let you know when I get things working and what the root causes were.

**Comment by waynepennington** [comment]
Uhg.

**Comment by waynepennington** [comment]
You've created a great tool.  We all look for easy fixes.  You've created a good one and thanks for sharing.  I had to do changes in my tooling environment and got it to work.  Again, my thanks for sharing your work.
