### ISSUE TITLE
Chrome browser compatibility issues under Windows 8.1

### ISSUE THREAD

**Issue by terrydb5** [skavanagh/KeyBox#165]
Use Chrome（version 51.0.2704） under Windows 8.1，when the web terminal output more content, the output will appear beyond the area，and not in the vertical alignment。

![image](https://cloud.githubusercontent.com/assets/14961217/17959046/6fae0dd4-6ad0-11e6-91a0-a8088c3441c2.png)

![image](https://cloud.githubusercontent.com/assets/14961217/17959060/841a48d2-6ad0-11e6-89b6-745e2ac3552f.png)

**Comment by skavanagh** [comment]
Are you resizing the browser window?  I can kind of make it happen if I do that.  Also, if you go to Terminal -> Reset Size does it fix it or is it still off?

**Comment by terrydb5** [comment]
The browser window's size is full screen，i donnt do resize operation.

let me try reset terminal size：
1、set bigger size
![image](https://cloud.githubusercontent.com/assets/14961217/17991554/4d8b99f4-6b72-11e6-9bc1-d69a1fda2d41.png)

2、reset origin size
![image](https://cloud.githubusercontent.com/assets/14961217/17991558/541130cc-6b72-11e6-90cf-a06b06f57acb.png)

3、set smaller size
![image](https://cloud.githubusercontent.com/assets/14961217/17991569/5fcce2b2-6b72-11e6-9900-9de5df663afe.png)

4、reset origin size
![image](https://cloud.githubusercontent.com/assets/14961217/17991575/68740c42-6b72-11e6-81c9-eae36938c687.png)


if i resize terminal window，the output content appears the same。

**Comment by terrydb5** [comment]
Hi，skavanagh，We locate the cause of the problem，the font led to abnormal display。

Windows doesn't default install “DejaVu Sans Mono”，when we change font to "Lucida Console", display is OK!
