### ISSUE TITLE
Auditing : unable to find code where single keystroke is executed for selected terminal.

### ISSUE THREAD

**Issue by preetampatil3d** [skavanagh/KeyBox#167]
Actually i was using default auditing but facing problems such as,
1. Huge database entries.
2. Output it was showing on audit page for single terminal is not proper (some special characters mixed up with commands).

Solution which i am trying is fetching full command and insert into DB on Enter key press.
**Can you please tell me exactly where command is executed in code**.

if i write any logic in SessionOutputUtil.java > getOutput . For multiple terminals its skips output, so i cant write any logic here. So i created hashmap here. and insert into DB in SecureShellWS.java > onmessage > on keyCode(13) that is on enter.

Also it would be better if tell how to use audit logging in this project.

Thanks in advance.

**Comment by preetampatil3d** [comment]
i have added one command as one entry instead of character wise entry to reduce huge db entries.

**Comment by dino0633** [comment]
Hi, I know it was a long time ago but could you please share the modification you performed on the source code in order to have command into the database rather that single keystroke?
