### ISSUE TITLE
External Authentication

### ISSUE THREAD

**Issue by jonnymccullagh** [skavanagh/KeyBox#17]
Feature Request: Would it be possible to add external authentication for user accounts e.g. ldap/AD so they can use the same combination as used elsewhere but the KeyBox specific stuff such as profiles and systems can remain in KeyBox?

**Comment by jordantrizz** [comment]
Upvote!

**Comment by rmkjr** [comment]
+1

**Comment by sibivk** [comment]
Cool, very cool! We have been using this a lot now, saves us tons of time!!! The only thing thats stopping us from mass deployment is LDAP... 
When creating a user, it would be outstanding if we could choose between internal and LDAP user authentication ...+1 here too.

**Comment by skavanagh** [comment]
Maybe two options for this.  

1. Like what @sibivk describes and still add users but the username would have to match the uid in LDAP (The baseDN and the rest of the connection would be in the properties file).  Full-privileged user would assign profiles from there.  

2. The baseDN and the connection would be in the properties file, but as users authenticate they are added as users in KeyBox.  The full-privileged user wouldn't have to actually create the user and could just assign them profiles.

I kind of like option 2.  It's not like you can do anything anyway if you login and don't have a profile.  I could even make it so you fail login if there are no profiles assigned.

**Comment by sibivk** [comment]
I agree with option 2. Cant wait to see it! Please feel free to reach out if you need any help testing.

**Comment by nox-do** [comment]
Who want's to work in this? shall we (hufsm), skavenagh or will you
(sibvik) do it?
 Am 26.02.2015 15:50 schrieb "sibivk" <notifications@github.com>:

**Comment by skavanagh** [comment]
@sibivk, @nox-do  - some help testing would be great!!

I put it on a branch for now

https://github.com/skavanagh/KeyBox/tree/2.80.00-SNAPSHOT

See https://github.com/skavanagh/KeyBox/tree/2.80.00-SNAPSHOT#enable-ldap
on how to setup

You can use this 
https://s3.amazonaws.com/kavanagh-keybox/keybox-upgrade-2_80.jar
```
java -jar keybox-upgrade-2_80.jar <whatever path to old DB>/keybox.h2.db
```
if you want to upgrade the your DB and use the existing data (make sure to backup first)

Be gentle!!! It's my first stab at this!

**Comment by sibivk** [comment]
I was very excited to test! I was able to build and look at the option. I tried playing around but.... In our LDAP environment, we are required to bind with a service account to search the LDAP. Looks like an additional option to put a service account/bind DN with password is required in the KeyBoxConfig.properties file

**Comment by skavanagh** [comment]
It should just binds as that user. 
```
uid=<username>,<baseDN>
```
You may want to make sure the baseDN is set correct b/c it needs to be the baseDN for the users and not the service accounts (b/c those are likely to be different)

**Comment by sibivk** [comment]
Unfortunately our LDAP environment is Active Directory and though I'm not a programmer, I looked into your code and see that you were using 'uid' attribute, to resolve the username in AD. I used a friend to change that to 'sAMAccountname' and rebuild, but that did not help. He pointed me to this example on how to implement similar code that works with AD. http://www.adamretter.org.uk/blog/entries/LDAPTest.java
Another idea maybe to put an additional switch in the properties file to specify between AD and OpenLDAP  implementations, so both type of environments can make use of your masterpiece!

**Comment by skavanagh** [comment]
@sibivk  - We should be pretty close.  I'll try and do some research over the weekend (wish I had a way to test with AD).  If I can figure out how to do the AD bind then we should be able to make it configurable.  Thanks for checking.

**Comment by skavanagh** [comment]
@sibivk - It's been updated to use JAAS so it should be more configurable https://github.com/skavanagh/KeyBox/tree/2.80.00-SNAPSHOT#external-authentication
 you may want to give it another shot.  Not sure if I have a good example for the AD configuration though.

**Comment by sibivk** [comment]
I think you're getting close, however in our AD environment we are not allowed to do anonymous binds. Looking at other JAAS implementations it seems as though there are two additional properties to specify in order to bind the credentials. They are ...
java.naming.security.principal="<binddn>"
java.naming.security.credentials="<binddn-password>"
We tried putting that in your configuration file under ldap-ad, however we keep getting the following error....
javax.security.auth.login.FailedLoginException: Cannot bind to LDAP server
It seems as though it is not taking the additional properties mentioned above. We got the above message when we turned on the debugging.

**Comment by skavanagh** [comment]
Strange! It shouldn't be doing an anonymous bind and those credentials should actually be set behind the scenes by the module you specify in the config file (com.sun.security.auth.module.LdapLoginModule)

Don't know if it helps, but there is some more examples here

https://docs.oracle.com/javase/7/docs/jre/api/security/jaas/spec/com/sun/security/auth/module/LdapLoginModule.html  

I'll try and search around tonight.

**Comment by skavanagh** [comment]
Ok maybe I lied!! If you have the 'userFilter' line in the config - it maybe doing an anonymous bind first.
Try just setting 'authIdentity' You should see something like this in the debug output
```
[LdapLoginModule] authentication-only mode; SSL disabled
```

**Comment by sibivk** [comment]
EUREKA!!!!
So we played around and finally found the configuration to get your product to work in our AD environment. Turns out we had to comment out the 'authidentity' and add three critical properties(in order to use bind credentials). Please find below the config block that worked for our environment(where anonymous binds are not allowed).
<pre>
ldap-ad {
        //AD example config - really have no clue here (Now you do!!! ;) )
    com.sun.security.auth.module.LdapLoginModule REQUIRED
    userProvider="ldap://<SERVER>:389/<BASEDN>"
    //authIdentity="{USERNAME}"
    userFilter="(&(samAccountName={USERNAME})(objectClass=user))"
    java.naming.security.authentication="simple"
    java.naming.security.principal="<BIND-DN>"
    java.naming.security.credentials="<BIND-DN PASSWORD>"
    useSSL=false
    debug=true;
};
</pre>

Eagerly waiting for your full release with AD LDAP integration!

**Comment by nox-do** [comment]
Thanks to both of you. Didn`t expect a solutíon that fast. Hope we can
provide some support regarding the configuration.
Am 03.03.2015 19:31 schrieb "sibivk" <notifications@github.com>:

**Comment by skavanagh** [comment]
@sibivk Glad you got it going!! - You may want to try with 
```
authzIdentity="{displayName}"
```
set so that when accounts are create on the keybox side it pulls the name (should work fine without it though).  Different option than authIdentity (notice the 'z' )  Thanks for all the help.

**Comment by soumypau** [comment]
Hi ..
I am running Keybox 2.85_02, and integrated it with an external LDAP.
I see a behaviour that when a user tries to login for the first time, the authentication fails saying no profile is assigned to the user. 

Is it possible to indicate a default project where users will be assigned on first time login ? 

-Soumyadeep

**Comment by skavanagh** [comment]
I think what would actually be nice here is having LDAP groups map to profiles in KeyBox. That way you are not assigning users to profiles after the login for the first time.

**Comment by soumypau** [comment]
I agree. Thats even better. 
Does this exist already ? Or it will be an enhancement .
-Soumyadeep

**Comment by skavanagh** [comment]
Doesn't exist unfortunately and would have to be an enhancement.

**Comment by halloamt** [comment]
You can do that with a filter like this one
  userFilter="(&(|(samAccountName={USERNAME})(userPrincipalName={USERNAME})(cn={USERNAME}))(objectClass=user)(memberOf=CN=KEYBOX,OU=GRUPPEN,OU=MyBusiness,DC=company,DC=local))"

**Comment by louisdj** [comment]
Any update on this topic?

**Comment by skavanagh** [comment]
@louisdj - Not much as far as mapping to groups in LDAP.  I've been experimenting with a new LdapLoginModule that comes with Jetty (it should pull back groups)

https://www.eclipse.org/jetty/documentation/9.4.x/jaas-support.html#_a_closer_look_at_jaasloginservice

but I haven't been able to get it working yet.

**Comment by skavanagh** [comment]
Profiles can be mapped to LDAP roles (based on profile/role name).  Added configuration example - https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/jaas.conf#L28-L49
