### ISSUE TITLE
KeyBox and hosts with "fishshell"

### ISSUE THREAD

**Issue by volands** [skavanagh/KeyBox#170]
I try to use KeyBox together with ssh-hosts running fishshell (instead of bash). I can add these hosts to KeyBox, under "Manage Systems" these are marked as "Success", under "Secure Shell" I can access via shell to these hosts. 

The problem is, that the authorized_keys file is not adjusted (key management ist enabled: keyManagementEnabled=true). If I switch on a host to bash-shell, everything works fine.

Are there well known issues in this context (problems with fishshell)?

**Comment by skavanagh** [comment]
Fish doesn't like how I used the logical 'and' when running the commands together. It was getting
```
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
```
I modified to chain the commands

**Comment by volands** [comment]
Great, thank you very much!
