### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by s3cur3n3t** [skavanagh/KeyBox#171]
I need to know how to reset the Web GUI admin password.

Is there anyway on command line I can do it?

Thanks for your help.

Best regards.

**Comment by skavanagh** [comment]
Another "Full access" user can reset it. Otherwise you will have to write something to update the password in the DB

**Comment by s3cur3n3t** [comment]
Ok. I don't have no other user with admin access. So I will do database access and reset admin user password. 

Thank you very much for your time.

**Comment by danghai174** [comment]
How can i change admin password by accessing database?

**Comment by agagasamuel** [comment]
Hello,

I'm have problem access my admin page in bastillion. How do I connect to the database to modify the password hash?
