### ISSUE TITLE
KeyBox suddenly stop working or it hangs at login.

### ISSUE THREAD

**Issue by preetampatil3d** [skavanagh/KeyBox#175]
When we promoted keyBox to production(External authentication using LDAP), after certain time (one to three days) application get below error and its hangs at login page.

```
[INFO] Stopped ServerConnector@30c716ce{SSL,[ssl, http/1.1]}{0.0.0.0:443}
[INFO] Stopped o.e.j.m.p.JettyWebAppContext@af913dc{/,
Cannot get a connection, general error
ERROR ExternalAuthUtil - org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, general error
```

But when we try to debug it on our development environment , it runs smoothly . never got such error.
On production connecting users are huge compared to development environment.

Thanks in advance.

**Comment by skavanagh** [comment]
You may want to try setting mixed mode as described here 

http://h2database.com/html/features.html#auto_mixed_mode

on the connection string

https://github.com/skavanagh/KeyBox/blob/master/src/main/java/com/keybox/manage/util/DSPool.java#L72

I'm going to make that more configurable soon.

Also, you may want to up the memory (JVM max heap) for jetty. If you are using the startKeyBox.sh it's set there.

**Comment by preetampatil3d** [comment]
Actually we are using jdbc:mysql and i am not finding feature like 'AUTO_RECONNECT' for mysql database.

**Comment by skavanagh** [comment]
Yeah mysql won't have an AUTO_SERVER setting. Have you tried increasing the max connections?

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L49

**Comment by preetampatil3d** [comment]
As you have mentioned we have increased connection pool size to 100 and observed system for crash for last few days.
Previously system was crashing/hangs every day (need to restart jetty every day) now frequency of issue is every 4-5 days.

Today we have increased JVM max heap size through maven. will observe crash frequency for few more days.

Thanks.

**Comment by skavanagh** [comment]
sounds like a DB connection isn't being closed and there is a leak somewhere (and may not notice when it runs as embedded).. I'll try and add some logging and figure it out.

**Comment by preetampatil3d** [comment]
After increasing  JVM max heap size  through maven and connection pool size problem has resolved. We have observed system for almost one month still system has not crashed/hang.

**Comment by skavanagh** [comment]
Glad to hear!!
