### ISSUE TITLE
Keybox behind NGINX reverse proxy

### ISSUE THREAD

**Issue by peelos** [skavanagh/KeyBox#181]
Hi,  

Thanks for a great app

Would love to get this working behind a Nginx reverse proxy, ideally with SSL 

Two working configurations:

  location ^~ /domain1noSSL {

        proxy_pass http://127.0.0.1:9091;

        proxy_set_header Host $host;

                proxy_set_header X-Real-IP $remote_addr;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        location ^~ /domain2withSSL {

        proxy_pass http://127.0.0.1:8659;

        proxy_set_header    Host                $host;

        proxy_set_header    X-Real-IP           $remote_addr;

        proxy_set_header    X-Forwarded-Proto   $scheme;

        proxy_set_header    X-Forwarded-Ssl     on;

        proxy_set_header    X-Forwarded-Host    $server_name;

        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

        }

Neither works for keybox

Would anyone know what needs to be specified to get this working? 

Thanks

**Comment by skavanagh** [comment]
This thread may help - https://github.com/skavanagh/KeyBox/issues/51

**Comment by peelos** [comment]
Thanks, I did check that thread but unfortunately the configuration didn't work for me.

**Comment by peelos** [comment]
Thanks, I did check that thread but unfortunately the configuration didn't work for me.

**Comment by peelos** [comment]
I did manage to get a connection to keybox using the following code:

location ^~ /keybox {
        proxy_pass https://127.0.0.1:8443/;
                proxy_read_timeout 1800s;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }

however url diverts to https://mydomain.com/login.action

instead of https://mydomain.com/keybox/login.action

if I enter https://mydomain.com/keybox/login.action directly then I am presented with the login screen with broken images:

<img width="286" alt="screen shot 2016-10-25 at 18 25 16" src="https://cloud.githubusercontent.com/assets/22773041/19694723/c8969304-9ae0-11e6-991b-6de28bff10c9.png">

and no login button

I think if I can get keybox to run as 127.0.0.1/keybox in the configuration i.e. change the base URL then this could be resolved..

I am not very experienced in coding, so was wondering if it is possible to edit this in the configuration somewhere? I am using Linux on a Qnap NAS and have SSH access to adjust any files.

many thanks

**Comment by skavanagh** [comment]
try editing jetty/webapps/keybox.xml and change 

`<Set name="contextPath">/</Set>`

to

`<Set name="contextPath">/keybox</Set>`

then change your nginx config to

`proxy_pass https://127.0.0.1:8443/keybox;`

**Comment by peelos** [comment]
fantastic, that worked! many thanks for your support.
