### ISSUE TITLE
SSH Gateway

### ISSUE THREAD

**Issue by lionel-deglise** [skavanagh/KeyBox#183]
Hi

I have servers hidden behind a reverse proxy. These servers have no WAN access. I'd like to login into them using my reverse proxy as SSH gateway. It works well using term. Is it possible using Keybox ?

Thanks

**Comment by skavanagh** [comment]
Yes - There are a couple of threads here on how to do that with apache and nginx

https://github.com/skavanagh/KeyBox/issues/181
https://github.com/skavanagh/KeyBox/issues/51
