### ISSUE TITLE
Systems and users association search

### ISSUE THREAD

**Issue by colandre** [skavanagh/KeyBox#184]
It happens often that collegues ask me to give them access to a specific system.
I have about 100 systems and 15 profiles in Keybox.
It is difficult for me to identify what profile is containing a system and associate a user to it.

On the other hand, it is difficult identifying what are all the profiles associated to a user.

It should be nice to have a way to
* search/get all profiles associated to a system
* search/get all profiles associated to a users

Thanks
Andrea

**Comment by skavanagh** [comment]
Yes - this sounds like a good idea.
