### ISSUE TITLE
Problem with Private Key Downloading

### ISSUE THREAD

**Issue by ManuelReyesV** [skavanagh/KeyBox#185]
Hello, when I choose to generate the ssh keys of the key box, the feature to download the private pair send me to:

https://192.168.56.101:8443/admin/downloadPvtKey.action?publicKey.keyNm=

that is a blank screen. Im doing some wrong??.

![capture](https://cloud.githubusercontent.com/assets/6993631/20145709/be765e40-a666-11e6-8eb1-89df251acf93.JPG)

2nd. Are you planning to add a key assignment function to an user ("single administrative account") from an Administrator account on future releases.

**Comment by symgryph** [comment]
I am having the same problem. Any purpose to the 'key' function? P.S. I LOVE keybox. I can provide a nice guide on setting it up within an azure environment using freebsd jails.......

**Comment by skavanagh** [comment]
Looks like the lastest version of struts is causing this to do an extra redirect.  Strange!

**Comment by skavanagh** [comment]
@ManuelReyesV - sorry forgot to answer.

> Are you planning to add a key assignment function to an user ("single administrative account") from an Administrator account on future releases.

Not planning on it... I don't want users setting keys for other users. "Full Access" users set profiles for "Administrative Only" users and everyone handles their own keys (although "Full Access" users can disable any user's key). 

I want to keep it so the user that owns the key either downloads it directly or generates it on their own.  That way it discourages private keys from being shared, sent over email, and other awful things. 

Hope this at least explains the rationale!
