### ISSUE TITLE
Same problem for me

### ISSUE THREAD

**Issue by symgryph** [skavanagh/KeyBox#186]
Also what is the purpose of the 'upload or generate key' function? Does it 'add' another authorized key to the 'shared' account that keybox manages?

**Comment by symgryph** [comment]
oops

**Comment by skavanagh** [comment]
Hi @symgryph 

> Also what is the purpose of the 'upload or generate key' function? Does it 'add' another authorized key to the 'shared' account that keybox manages?

Yes it does.. It's doing key management for when admins ssh directly to their servers.

"Full access" users can add "administrative only" users, create profiles, assign systems and users to profiles. "Administrative only" users can add their own ssh key based on the profiles they have assigned. "Full access" users can disable any key that any user has added. They can also add their own keys to all systems or any systems under a profile.

Everyone handles their own keys to discourage sharing and reuse.

**Comment by symgryph** [comment]
Is there any way I could force uniquely generated keys? I want to use the key fingerprints to uniquely identify users using the shared system account.

Thomas J Munn

**Comment by skavanagh** [comment]
If forceUserKeyGeneration=true in the KeyBoxConfig.properties, then keybox generates the key (so the user can't set it explicitly). And it will always be unique per user. Also it should add the username as a comment in the authorized_keys file.

**Comment by symgryph** [comment]
So if I set both to true then I will be ok from an audit point of view?

Thomas J Munn

**Comment by skavanagh** [comment]
I'm not sure how you are you are tracking keys to users, but if forceUserKeyGeneration=true then the keys that are generated should always be unique.

**Comment by symgryph** [comment]
I am willing to help write some documentation in the wiki, but I was wondering if you could help me. I was wondering if we could talk sometime and I could learn how to do various things the people pester you about.

I might also be able to help perhaps with some YouTube videos as well. If you're willing to do this what times work for you? And what time zone are you in I didn't notice. I'm guessing you're in Europe.

**Comment by skavanagh** [comment]
Yeah.. if you are willing to do that, it would be great I'll email you my contact info.  

Nope.. I'm in Cleveland (**Not Europe)

**Comment by symgryph** [comment]
Any way I can Skype or talk with you? Upgrade going badly…sadness.
