### ISSUE TITLE
Feature Request (not sure where to put these) - Let's Encrypt?

### ISSUE THREAD

**Issue by symgryph** [skavanagh/KeyBox#189]
It would be really coolio if we could use 'lets encrypt' for no more self-signed warnings. Willing to be guinea-person for this if you want. I have public sites I can test.

**Comment by skavanagh** [comment]
You can't pre-install a valid cert b/c you don't know what the domain the
certificate needs to be.

I've always pointed ppl to the jetty docs (or other container)
