### ISSUE TITLE
Export logs

### ISSUE THREAD

**Issue by letienne** [skavanagh/KeyBox#19]
Hello,

This project looks very promising.

It would be almost perfect if it was possible to export logs to file (or an external DB), to be processed in another context (SIEM, Splunk, Logstash, etc.). Or even to write them directly to file.

Is that something planned ? Possible?

Thanks !

Regards,

**Comment by skavanagh** [comment]
This can be done now (kind of) by setting an appender for log4j

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/log4j.xml#L14-L26

and defining the auditLogAppender property

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L22
