### ISSUE TITLE
installing the proper java version

### ISSUE THREAD

**Issue by aristosv** [skavanagh/KeyBox#191]
I tested this under windows and its working just fine. Now I am trying to make it work under Debian, but I'm having trouble installing the proper java versions. Its confusing because there's openjdk, javajdk, oraclejdk, there's rpm files, and there's some packages that can be installed with apt-get.

So what's the correct way to install the proper packages, preferably using apt-get, in order to get this software to work under Debian?

Thanks

**Comment by skavanagh** [comment]
It doesn't matter.. as long as you are on version 8 or greater, any of the JDKs found in apt should be fine.  On Ubuntu I've been using 'openjdk-8-jdk'
