### ISSUE TITLE
Request Audit Logs not be deleted

### ISSUE THREAD

**Issue by cplvic** [skavanagh/KeyBox#194]
I noticed that when I deleted users (or maybe in combination with systems) from KeyBox, the audit logs for the users went away as well. 
Audit trails are important even if the user is removed for [x] reason. Could you make it so Audit Session are retained regardless of whether the user exists in the KeyBox user db?

**Comment by skavanagh** [comment]
+1 I agree. It's doing it after you delete the system.

**Comment by lucapalano** [comment]
@cplvic as you probably have already seen, it's available in 2.89.00. So, this may be closed.

Luca
