### ISSUE TITLE
Scrollback History adjustment

### ISSUE THREAD

**Issue by cplvic** [skavanagh/KeyBox#195]
Is there a way to control/define scrollback history.
Some of my users like to have at least 100k lines so they can scroll and review [x] output

**Comment by skavanagh** [comment]
There isn't a property for it, but you should be able to set it here -

https://github.com/skavanagh/KeyBox/blob/050779a5a6de6e1ee0bb21c629d4b7
39c10d125d/src/main/webapp/_res/js/tty/term.js#L395

**Comment by cplvic** [comment]
that's awesome. I should have looked there first.
Thanks again!
