### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by prozit** [skavanagh/KeyBox#201]
Hi,

When running a new installation of KeyBox on a CentOS 7 machine, I am able to create new systems and profiles, but I am not able to create new users. When I try to do so, the application informs me that the password is not strong enough, even though I have used between 10 and 15 characters with small caps, capitals, alphanumeric characters and numbers.

I believe this might be a bug in the application.

Kind regards,
Francis Claessens

**Comment by skavanagh** [comment]
Password complexity is set here - https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L35-L38

**Comment by symgryph** [comment]
Its a regex, upper, lower, # and special minim length

**Comment by lucapalano** [comment]
Hi @prozit,

I recently fixed a bug (#257) . That bug regarded the characters used in the password. I recommend you to upgrade to the next version (2.90.03 when it will be released) and check if the behaviour will persist.

Luca
