### ISSUE TITLE
Login Reprompted at first attempt - Second attempt works

### ISSUE THREAD

**Issue by colandre** [skavanagh/KeyBox#203]
Hello @skavanagh,

since the upgrade to version 2.88.00 I'm experiencing this strange behavior.
At the login page the first attempt (with correct credentials and OTP) always redirect to the same login page.
At the second attempt, you are correctly logged in Keybox.

I'm opening this issue now because I thought it was just a problem strictly related to me, and some misalignment in my phone (OTP generator) and the server. But other colleagues reported this, so I decided to open this issue.

I noticed I have the problem with Chrome (version Version 55.0.2883.87 m).
I have no problem with Firefox (v50.1.0) and Internet Explorer (v 11.0.9600.18537)

Are you experiencing the same or it could be related something in my environment configuration?

Thanks

**Comment by skavanagh** [comment]
Do you have a reverse-proxy in the mix? It sounds like it maybe a combination of that and the CSRF token that was added in 2.88. You can view source on the login page and see if the token is there (should be in a hidden for field). Also, could try to hit keybox without the reverse-proxy.

**Comment by colandre** [comment]
Hello @skavanagh ,
thanks for your reply.

Yes, I'm running Keybox behind a reverse proxy (Apache with ProxyPass).
As you mentioned, I think the problem is the CSRF token.
If I access Keybox directly the hidden form field is populated at the first time.
`<input` name="_csrf" value="78R1YAX75TIGZJ1N3DFUD80WICAUZOKR" id="loginSubmit__csrf" type="hidden">

When I access normally through Apache, the first time page is accessed, the hidden field is empty
`<input type="hidden" name="_csrf" value="" id="loginSubmit__csrf">

Is there something I can do at reverse-proxy level to prevent this behavior?

Ps.
I think my analysis on other browser was wrong, so all are affected by this issue.

Thanks
Andrea

**Comment by skavanagh** [comment]
It sounds like it's not hitting the initial login.action to set the token.

https://github.com/skavanagh/KeyBox/blob/master/src/main/java/com/keybox/manage/action/LoginAction.java#L53-L62

are you able to get to /login.action through the reverse-proxy?

**Comment by colandre** [comment]
Yes, I'm able to get the /login.action page through reverse-proxy. if I reload the page I get a page with csrf field correctly populated.

I tried to clear all browser data and I noticed this.
If I perform the login page GET request (/login.action) my browser do not send any JSESSIONID cookie due to no cookies available. In this case I do not obtain a token from Keybox for csrf field.

If I refresh the page, my browser send the cookie received with the first page load. 
In this case the csrf field is correctly populated with a token and the login is completed correctly.

I saw in your referenced code that the session is taken from the request (servletRequest.getSession()) and I think that the problem is related to this.

I have to correct again my analysis. I retried to directly access to login page throught jetty cleaning all browser cookies, and, in this way, skipping the reverse-proxy. The login page received has no token populated for csrf field.

Are you able to replicate this behavior?

Thanks for your time.
Andrea

**Comment by skavanagh** [comment]
Yeah- I've got it now. If I go to '/' things work as expected, but if I go directly to '/login.action' then it's not setting the token on the login page.

**Comment by skavanagh** [comment]
Yes - this is exactly what is going on JSESSIONID is not present when going to the login page directly.  Should be fixed.  Thanks @colandre !

**Comment by colandre** [comment]
Hello @skavanagh,
thank you for your time.

I just installed Keybox version 2.88.01 and the login page works like a charm.
