### ISSUE TITLE
404 on creating SSH Terminal (/admin/terms.ws)

### ISSUE THREAD

**Issue by KashifSaadat** [skavanagh/KeyBox#207]
Hi there,

Since upgrading from v2.86.00 to v2.88.01 I have encountered the following issue:
When selecting an instance to create an SSH Terminal and navigating to the next page, the terminal window only shows the title bar and no area is present to type content. My web browser returns a 404 Not Found when attempting to access the following resource: `wss://[internal-domain]/admin/terms.ws?t=1488799546358`

I followed the v2.86.00 migration steps as suggested on the Release page. Any help would be greatly appreciated!

Thanks,
Kash

**Comment by skavanagh** [comment]
It sounds like websockets is disabled.  Are you connecting directly to KeyBox or through a reverse-proxy?  If you are connecting directly to KeyBox and still getting this make sure the jetty/start.ini file has both
```
--module=client
--module=websocket
```

**Comment by KashifSaadat** [comment]
Hey @skavanagh, during the upgrade I changed my routing to go via a proxy and that caused the issue. My traffic was interpreted as HTTPS instead of SSL/TCP, and it was failing on the attempt to establish a secure websocket connection because of this.

All resolved now, thank you for the speedy response! :)
