### ISSUE TITLE
Hosts on Ports other than 22

### ISSUE THREAD

**Issue by cudimax** [skavanagh/KeyBox#208]
I seem not to be able to connect to any Hosts with Ports other than 22.
Is there a work-around for connecting to alternative ports ?

![screenshot1488879291 2x](https://cloud.githubusercontent.com/assets/2333424/23650251/c81631ce-0321-11e7-9191-cdcfef40e60a.png)

**Comment by skavanagh** [comment]
The ssh server on the host would have to be configured to listen on that alternative port.

**Comment by cudimax** [comment]
Thank you for the update. 
- Richard
