### ISSUE TITLE
cookies sent by the application missing 'httpOnly' attribute

### ISSUE THREAD

**Issue by rpfilomeno** [skavanagh/KeyBox#213]
This was a scan result from OpenVAS:

> Summary

> The application is missing the 'httpOnly' cookie attribute
> 
> Vulnerability Detection Result
> The cookies:
> 
> Set-Cookie: JSESSIONID=***replaced***;Path=/;Secure 
> 
> are missing the "httpOnly" attribute.
> Solution
> Solution type: Mitigation Mitigation
> 
> Set the 'httpOnly' attribute for any session cookie.
> 
> Affected Software/OS
> Application with session handling in cookies.
> 
> Vulnerability Insight
> The flaw is due to a cookie is not using the 'httpOnly' attribute. This allows a cookie to be accessed by JavaScript which could lead to session hijacking attacks.
> 
> Vulnerability Detection Method
> Check all cookies sent by the application for a missing 'httpOnly' attribute
> 
> Details: Missing `httpOnly` Cookie Attribute (OID: 1.3.6.1.4.1.25623.1.0.105925)
> 
> Version used: $Revision: 5270 $
> 
> References
> Other:	https://www.owasp.org/index.php/HttpOnly
> https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)

If there a way to set this by default? I tried adding to web.xml but it didnt work:

```
<session-config>
        <cookie-config>
            <!--             
            Specifies whether any session tracking cookies created 
            by this web application will be marked as HttpOnly
            -->
            <http-only>true</http-only>
        </cookie-config>
    </session-config>
```

**Comment by skavanagh** [comment]
![jsesson_httponly](https://cloud.githubusercontent.com/assets/3192731/23923406/ef3e1526-08dc-11e7-9ea6-3dfadbc6c1fb.png)
that configuration seems to work ok for me.

**Comment by skavanagh** [comment]
Thanks @rpfilomeno
