### ISSUE TITLE
Increase Session Time out for the Browser?

### ISSUE THREAD

**Issue by hobleyd** [skavanagh/KeyBox#215]
Hello,

I tried setting sessionTimeout=1440 in the KeyBoxConfig.properties file, but it still seems to timeout after 15 minutes. Is there another setting I should be using?

Cheers,
David

**Comment by skavanagh** [comment]
sessionTimeout is the timeout for users logged into the application. Is the timeout occurring when you are in the terminals?  

If the timeout is between the client and keybox,  is there a device out front of Keybox that could be disconnecting? Keybox uses web-sockets, so firewalls, load-balancers, reverse-proxies, etc.. sometimes timeout persistent connections after so long.  I've had that happen to folks on the EC2 side https://github.com/skavanagh/EC2Box/issues/27#issuecomment-221137860  

If it's between keybox and the server, then it could be a setting in the /etc/ssh/sshd_config

**Comment by hobleyd** [comment]
No - it is the Web Application which is a problem (I think). The symptoms are:

I log in to the Web application; open a terminal to one of my machines; leave it alone for 15 minutes (or so); when I come back, I can't interact with the terminal and if I click on "Exit Terminals" then I get dumped back to the login page. Hence my assumption it is the application timeout.

It sounds like sessionTimeout is the correct variable then. Any idea why it might be being ignored? I am using an Apache reverse proxy in front of it, yes.

**Comment by skavanagh** [comment]
The code is pretty straight forward around this and it looks like it's function as it should.  Does it happen without the reverse-proxy?  

It could also be CSRF protection. Having two users logged into the same account or opening tabs in a new window can this.

**Comment by hobleyd** [comment]
Hmmm. Interesting; I am finding some strange behaviour with this; I'll test some more and reopen the ticket if required.
