### ISSUE TITLE
Error 404 after upgrading from 2.88.02 to 2.89

### ISSUE THREAD

**Issue by Choukajohn** [skavanagh/KeyBox#217]
Hi,
I'm using version 2.88.02.
I followed procedure to upgrade from version >=2.87 to 2.89 and this doesn't work, I have an Error 404 in the web browser.

```
Error 404 - Not Found.

No context on this server matched or handled this request.
Contexts known to this server are:
/ ---> o.e.j.w.WebAppContext@18eed359{/,file:///home/choukajohn/KeyBox-jetty/jetty/keybox/,UNAVAILABLE}{/home/choukajohn/KeyBox-jetty/jetty/keybox} [failed]
```

I tried this fix https://github.com/skavanagh/KeyBox/issues/137 and I always have the same error.

Someone have an idea ?
Thanks.

**Comment by skavanagh** [comment]
Are there any other errors that show up? Also, in your old installation did you modify the jetty/webapps/keybox.xml and change the context?

**Comment by Choukajohn** [comment]
No there is no other error, when I start the KeyBox "service" through​ SSH everything is ok.
I didn't modify anything except KeyBoxConfig.properties.

**Comment by skavanagh** [comment]
Could be permissions. Are you starting it as a different user when it's ok?

**Comment by Choukajohn** [comment]
No I have always used the same user even for running upgrade. Maybe I have to use root for upgrade ? But I have message saying everything is ok after upgrading.

**Comment by skavanagh** [comment]
Ok - There is a new configuration property that you may need to add (and not having it causing this) https://github.com/skavanagh/KeyBox/commit/7f0bc33203843f20666149d68ccd7f38bb14c891#diff-492f27a5044cce8470c2303ab98a06f5
so if you are using the properties file from the old version, you need to make sure it's there.

**Comment by Choukajohn** [comment]
It works !
Thanks for your help !

**Comment by yanchhuong** [comment]
you need to   add in pom.xml like below : 
**** check your appengine version *** 

 <plugins>
...
             <plugin>
		      <groupId>org.eclipse.jetty</groupId>
		      <artifactId>jetty-maven-plugin</artifactId>
		      <version>9.4.8.v20171121</version>
		      <configuration>
			    <scanIntervalSeconds>10</scanIntervalSeconds>
				<contextHandlers>
				   <contextHandler
				        implementation="org.eclipse.jetty.maven.plugin.JettyWebAppContext">
						<war>${project.basedir}/target/demo-${project.version}.war</war>
				        <contextPath>/</contextPath>
				   </contextHandler>
				</contextHandlers>
		      </configuration>
        </plugin>
  </plugins>
