### ISSUE TITLE
Adding private keys

### ISSUE THREAD

**Issue by chriscowley** [skavanagh/KeyBox#22]
Any plans to for this? I tend not to allow password access to systems, so authentication by RSA key pair would be a great feature

**Comment by rgv151** [comment]
i agree, store key & passpharse in config file is easy for other to see them

**Comment by skavanagh** [comment]
If you set the key and passphrase in the config file, when keybox is started they will be encrypted and loaded into its database.  The passphrase is then removed from the config file (I could remove the path to the keys too).  Once this is done the key can be removed from the system running keybox entirely and what is in the config file doesn't matter. Maybe I'll update the README. Thanks!

**Comment by agagasamuel** [comment]
@skavanagh 

I'm trying to add a new system that already has its own key pair and would like to complete the enrollment/authentication of the new system using its private key rather than password. 

Is this possible?

Password authentication is disabled on the system.

Regards.
