### ISSUE TITLE
Admin user password reset

### ISSUE THREAD

**Issue by mil10jose** [skavanagh/KeyBox#225]
I'm setting up a keybox server and after a stop and start startKeyBox.sh, the admin password is not working any more. I rebuild the box before when the issue occurred to avoid any miconfig.  Thanks in advance.

**Comment by skavanagh** [comment]
Another "Full access" user can reset it. Otherwise you will have to write something to update the password in the DB. It could be the OTP code and the clock on the system running keybox off.
