### ISSUE TITLE
How to disable 2fa ?

### ISSUE THREAD

**Issue by Merrick28** [skavanagh/KeyBox#226]
Hello,

my phone just broke, so I lost my google authentication access. How can I remove the 2fa (or reset it ?) to gain access to my keybox again ?

**Comment by skavanagh** [comment]
in the jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties file set 'oneTimePassword' to 'disabled' and login with the locked out user.
https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L28

Also, before you re-enable the OTP, create a new "Full access" user that can reset the locked out user's OTP

**Comment by Merrick28** [comment]
Thanks a lot. Would it be a good idea to put this tip in the wiki ? If yes I can manage it.

**Comment by skavanagh** [comment]
@Merrick28 Yes - I think so.. I've had a couple ppl ask for help when this happens.

**Comment by Merrick28** [comment]
Done (quickly, hope syntax is ok for you).

**Comment by skavanagh** [comment]
Looks good! Thanks!
