### ISSUE TITLE
LDAP  auth

### ISSUE THREAD

**Issue by edouardpernot** [skavanagh/KeyBox#234]
Hello, 

Here's my config .

ldap-ol {
    //openldap auth first example config
    com.sun.security.auth.module.LdapLoginModule REQUIRED debug=true
    userProvider="ldap://LDAP.ACME.COM:389/ou=People,o=ACME.COM"
    authIdentity="{USERNAME}"
    userFilter="(&(mycustomattribute={USERNAME})(manager=uid=XXXXX@ACME.COM.,ou=People,o=ACME.COM))"
    authzIdentity="{cn}" //set this to return full name
    debug=true
    useSSL=false;
};

I double check connectivity and filter with  ldapsearch and it works
ldapsearch -x -h LDAP.ACME.COM -p 389 -b "ou=People,o=ACME.COM"  "(&(mycustomattribute={USERNAME})(manager=uid=XXXXX@ACME.COM.,ou=People,o=ACME.COM))"

The debug logs doesnt tell me much jetty/keybox/WEB-INF/classes/log4j2.xml 
I enabled debug level but no luck beside 
javax.security.auth.login.LoginException: java.lang.NoClassDefFoundError: org/eclipse/jetty/jaas/callback/ObjectCallback

I tried multiple things but I must have missed some tiny detail .
If you can help me that would be great. 

Thanks
Edouard

**Comment by skavanagh** [comment]
Are you running the server in Jetty?  That library should come with jetty.  If you are running another web server you may have to download the jar

https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-jaas/9.4.5.v20170502

 and add it to the WEB-INF/lib directory

**Comment by edouardpernot** [comment]
Yep I'm running  the server in Jetty.
