### ISSUE TITLE
Auth Users LDAP and SSH

### ISSUE THREAD

**Issue by Viox-LJ** [skavanagh/KeyBox#239]
Hi, i have a problem with the SSH Sessions. I have a Kerberos on all my servers and the same user/pass used on all Servers for access from SSH.

Need know if this is possible with this solution.

The user login on the KeyBox and select the server and when open the connection use your user and all users use your username/password.

This is possible?

BR
Santiago

**Comment by skavanagh** [comment]
Well it's going to use the user that is setup when you register the system, but it will fail back and prompt for a password if the ssh key authentication fails.

**Comment by Viox-LJ** [comment]
I dont understand what is the metod for this. Can you help me with understand this part?
Thx

**Comment by skavanagh** [comment]
I'm basically saying you can't set the username on the fly, since the user it authenticates with is set when registering the system.
