### ISSUE TITLE
Issue With Creating Scheduled Task

### ISSUE THREAD

**Issue by jrv912** [skavanagh/KeyBox#244]
Is there a known issue where you can't start the startKeybox.bat file via a scheduled task (at startup)?

Currently someone has to be logged on and manually start the bat file, while staying logged into the box to keep Keybox running.  Is there a workaround for this?  I have a scheduled task created, but when it run its doesn't actually open the cmd prompt and start the bat file.

thanks!

**Comment by skavanagh** [comment]
Those scripts are just for convenience. If you need jetty running as a service you should refer to their documentation.  I think this should help - http://www.eclipse.org/jetty/documentation/9.4.x/startup-windows-service.html

**Comment by jrv912** [comment]
thank you!
