### ISSUE TITLE
Please add Lets Encrypt

### ISSUE THREAD

**Issue by jiri001meitner** [skavanagh/KeyBox#245]
Please add Lets Encrypt.

**Comment by skavanagh** [comment]
Let's Encrypt (or whatever CA) has to issue a certificate for you, attached to a domain you own, and it has to be installed in Jetty by you.

Here is how to install in jetty - 
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-ssl.html#loading-keys-and-certificates

**Comment by SyFizz** [comment]
Hello !
I was searching for how to install a Let's Encrypt certificate in Jetty, to use with Bastillion.

I found this tutorial : https://www.sorcerers-tower.net/articles/configuring-jetty-for-https-with-letsencrypt
That works very well.
