### ISSUE TITLE
Storage location of keybox.jceks

### ISSUE THREAD

**Issue by tobru** [skavanagh/KeyBox#248]
The key store file `keybox.jceks` is stored on a place which makes it very hard to persist when deploying KeyBox f.e. on OpenShift.

All persistent data of KeyBox seem to be stored under `keybox/jetty/keybox/WEB-INF/classes/keydb/` (afaics) but `keybox.jceks` under `keybox/jetty/keybox/WEB-INF/classes/keybox.jceks`. This path is not persistent and everytime the container gets re-deployed it loses it's jceks file. Please make this path either configurable or move the file to the `keydb` directory.

**Comment by skavanagh** [comment]
Ok - I can see that.. What about the KeyBoxConfig.properties and jaas.conf (if you use it)?

**Comment by tobru** [comment]
Of course it would be great if the location could be configured of these files, but as I generate the file `KeyBoxConfig.properties` during container startup (see https://tobru.ch/keybox-on-openshift/ for more information) I don't care much. What would be much more important: Configuration of KeyBox should be possible using environment variables, this would make things much easier. Should I open a new issue for that?

**Comment by skavanagh** [comment]
Added a JAVA_OPTION for this.
```
-DCONFIG_DIR=\<whatever dir\>
```
it will move the jaas.conf and KeyBoxConfig.properties files there too.
