### ISSUE TITLE
Details on credentials storage?

### ISSUE THREAD

**Issue by 4oo4** [skavanagh/KeyBox#249]
Can someone give me some details on how SSH private key passwords are stored in KeyBox? I'm mainly looking to use this for key management but before I installed it and started feeding it my keys, I wanted a better understanding of how everything is stored so I know how to properly protect the app.

My main concern was that someone would be able to retrieve private keys and their passwords if they were able to dump the database. I'm guessing that KeyBox was designed to prevent that from happening but wanted to know for sure.

**Comment by skavanagh** [comment]
For SSH key management, KeyBox only stores the public keys. No private keys stored for this whatsoever. 

There is only one private key that is ever stored and that is the one KeyBox uses to connect. Here is the details on how it's generated and stored.

On first startup:
-The private SSH key is generated using a random UUID as a passphrase.
-A 128 bit AES encryption key is generated and stored in a newly created keystore called keybox.jceks.
-The user is prompted to enter database credientials.
-An embedded H2 database is created (AES encrypted). The DB credentials are encrypted with the key in the keystore and set in the KeyBoxConfig.properties.
-The private SSH key and passphrase is encrypted using the AES encryption key in the keystore and stored in the embedded H2 database (the public key is also stored).
-The private key is then deleted from the system.

Using the application:
-When a system is registered, KeyBox adds the public key that was generated above.
-KeyBox uses the private key generated above to access the systems when using terminals. 
-It also uses this private key with key management and setting the public keys for the users in the appliction.
-There is a function of key management where users can generate a key, download the private, and the public is pushed to systems in their profile.  Once that download request happens, the private key goes away. KeyBox only stores the public key and does not store the private.

**Comment by skavanagh** [comment]
It's basically doing number 5 in the link below (except the database is on the host b/c it's embedded)

http://security.stackexchange.com/questions/12332/where-to-store-a-key-for-encryption?answertab=votes#tab-top

**Comment by 4oo4** [comment]
Just what I was looking for, thanks!
