### ISSUE TITLE
Some more example regex for passwordComplexityRegEx

### ISSUE THREAD

**Issue by ToeiRei** [skavanagh/KeyBox#250]
I was thinking as we already use OTP Passwords, we could lower the password complexity rules. But I'm pretty bad with regex. Not sure about others, but giving a few examples in the documentation wouldn't hurt I'd say.

**Comment by colandre** [comment]
Hello @ToeiRei ,

you can easily find regular expressions for password check or enforcement online.
For example here you can find a good library: [RegEx101](https://regex101.com/library?orderBy=RELEVANCE&search=password%20check)

**Comment by ToeiRei** [comment]
I always manage to crash the program having regex errors.

**Comment by colandre** [comment]
Hello @ToeiRei,

please note that some characters needs to be quoted with a backslash.
For example: "\d" that means every chars representing a number, must be written as "\\d"
Same thing with the comma, so "," becomes "\,"

What enforcement are you trying to obtain? E.g.
- at least one lowercase
- at least one uppercase
- minimum length = 6
- maximum length = 16

**Comment by ToeiRei** [comment]
I'm trying something like "anything above 6 characters is fine" as we're using OTP.
` passwordComplexityRegEx='.{6\,}'` doesn't work as expected

**Comment by colandre** [comment]
You could try with this:
`passwordComplexityRegEx=(.{6\,})`

**Comment by ToeiRei** [comment]
that did work. Looks like it doesn't like quotes. Guess that's a start to work from now.
