### ISSUE TITLE
ecdsa keys seem to be a problem as master key

### ISSUE THREAD

**Issue by ToeiRei** [skavanagh/KeyBox#252]
Log says
```
2017-10-03 14:52:46,400 ERROR EncryptionUtil - javax.crypto.BadPaddingException: Given final block not properly padded
javax.crypto.BadPaddingException: Given final block not properly padded
```
while RSA keys just work.

Alpine openjdk8 Image / docker

**Comment by skavanagh** [comment]
You have to change the key length too https://github.com/skavanagh/KeyBox/issues/223#issuecomment-299431529

**Comment by ToeiRei** [comment]
did so, but it got me the password fallback.

**Comment by skavanagh** [comment]
I would check your sshd logs on the server. I've read some linux distros may disable ECDSA b/c of patient concerns. The logs should tell you if it's unsupported.

https://wiki.archlinux.org/index.php/SSH_keys#ECDSA

**Comment by ToeiRei** [comment]
Using my private ecdsa keys works. The error message looks like keebox couldn't decrypt the private key.

**Comment by skavanagh** [comment]
Are you using a custom key? or did KeyBox generate it?

**Comment by ToeiRei** [comment]
KeyBox generated it.

**Comment by skavanagh** [comment]
huhh.. maybe the passphrase isn't being set correctly. Does the KeyBoxConfig.properties have
```
#default passphrase, leave blank for key without passphrase
defaultSSHPassphrase=${randomPassphrase}
```

**Comment by ToeiRei** [comment]
I am just wondering why it worked with RSA/4096 keys. - `defaultSSHPassphrase=${randomPassphrase}`  is set.

**Comment by ToeiRei** [comment]
Feel free to look at https://github.com/ToeiRei/sshKeybox-docker/blob/master/start.sh - that way the config gets written at the first start of the container.

**Comment by skavanagh** [comment]
I'm able to recreate this. I think it maybe bug / incompatibility between Jsch and OpenSSH

https://sourceforge.net/p/jsch/bugs/90/

**Comment by skavanagh** [comment]
Actually this fixes it - https://sourceforge.net/p/jsch/bugs/107/

I'll have to overload Jsch libraries signature class and set it to use SHA384withECDSA

**Comment by skavanagh** [comment]
I'm not sure if I'll leave it like this, but it should fix for now.  Hopefully JSch updates this soon. Thanks for finding this.

**Comment by ToeiRei** [comment]
I always tip into such bugs. One of my talents....
