### ISSUE TITLE
Show username in header

### ISSUE THREAD

**Issue by willsgrigg** [skavanagh/KeyBox#253]
Hello,

It would be nice if the username was displayed in the header to make it clear what account you are logged into. This would help to in instances where the user is switching between accounts, adding users to profiles and then adding that profile to their own keys.

Thanks.

**Comment by lucapalano** [comment]
Hi @willsgrigg,

I see your point. @skavanagh @willsgrigg what do you think of this mockup?

![keybox-user-mockup](https://user-images.githubusercontent.com/1812530/32619587-839848f8-c57b-11e7-849a-b76328ae06da.PNG)

"User", in the header, is the fake username I used as example in the mockup.

Thanks,
Luca

**Comment by skavanagh** [comment]
+1 Yes - Looks good to me.

**Comment by willsgrigg** [comment]
+1 Yep, that does the job!
