### ISSUE TITLE
Unable to create passwords with special characters

### ISSUE THREAD

**Issue by lucapalano** [skavanagh/KeyBox#257]
Hi @skavanagh,

The character **£**, when used in a password, causes the following error:
> [WARNING] /manage/saveUser.action org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content

<img width="328" alt="error" src="https://user-images.githubusercontent.com/1812530/33293803-4ee167be-d3ce-11e7-9155-5ac30fd4e713.png">

It cannot be considered a special char to use into a password. However, this is a minor bug. I opened this issue in order to trace it in case someone will incur in this error while trying to set a password for a user with that special char.

Luca

P.s.: I found a similar behavior with double quote char. I added a double quote into a password but it looks like if it was not present.

**Comment by skavanagh** [comment]
Not completely sure!  Maybe something with the jetty character encoding.
