### ISSUE TITLE
Upgrade From 2.90.01 to 2.90.02 Loses Data

### ISSUE THREAD

**Issue by jhamilt5** [skavanagh/KeyBox#260]
I am attempting to upgrade from `2.90.01` to `2.90.02` and preserve data (login info, systems, public keys, etc.)

I'm running on Ubuntu 16.04 LTS with the following java information
`openjdk version "1.8.0_151"`
`OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)`
`OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)`

Here are the steps I've taken so far:

- Downloaded keybox-jetty-v2.90_02.tar.gz
- Extracted and copied to target system
- Copied `2.90.01` **keydb** directory to the `2.90.02` equivalent path
- Copied the `2.90.01` **keybox.jceks** file to the `2.90.02` equivalent path
- Started up `2.90.02` version

I cannot login at all. The default admin login, my changed admin login, and all other user accounts are not accessible.

Did I miss something?

**Comment by skavanagh** [comment]
You can either copy the KeyBoxConfig.properties to the new installation or add the DB credentials to the new installation's file in clear text (it will encrypt it when it start)

**Comment by jhamilt5** [comment]
That did the trick. Thanks!
