### ISSUE TITLE
Keybox Hanging on Aerohive Switch

### ISSUE THREAD

**Issue by baggar11** [skavanagh/KeyBox#261]
We use Keybox to access our Aerohive gear even though they don't support key based authentication. The APs seem to work fine after manually sticking in the password everytime. The switches make Keybox hang. During adding the switch as a system and when trying to connect to the switch.

I can't seem to track down any log files that Keybox may be using or figure out a way to troubleshoot what's going on during the connection.

**Comment by skavanagh** [comment]
Should go to std error. Some of the logging around SSH connections is at lower logging levels. Try and set this

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/log4j2.xml#L32

to 'info' and see if you get an error

**Comment by baggar11** [comment]
So I set "info" level logging in /KeyBox-jetty/jetty/keybox/WEB-INF/classes/log4j2.xml. Restarted Keybox and pulled up the Aerohive switch. I tailed syslog and nothing came out. Then tried setting the logging level to debug. No dice. Still just hanging with no log action.

**Comment by skavanagh** [comment]
Huh.. Is this what it is doing?

https://github.com/skavanagh/KeyBox/issues/132

It happens when websockets is being blocked. You should see an error on the client in the javascript console.

**Comment by baggar11** [comment]
Doesn't appear to be. I'm not seeing any blocks in our firewall logs relating to the switch IP. Also, I'm not seeing the start of a session opening. Keybox just starts spinning in the browser. Ultimately, I have to hit refresh and then Keybox kicks me back out to the login screen.

![keybox-issue](https://user-images.githubusercontent.com/4692679/33951089-e8f44b9e-dfe2-11e7-801c-d2cbbc154e3b.png)

**Comment by skavanagh** [comment]
Sounds like it's just hanging and timing out. You could try and run an ssh client to the AP from the server hosting keybox, that way you can determine if the issue is outside the application.

**Comment by baggar11** [comment]
SSH via the CLI works fine. Although, when a "logout" or "quit" command is issued, it seems to hang the terminal. I'm starting to wonder if that behavior is related to why Keybox is having an issue with it. I would have thought Keybox would have a logout issue too, instead of a login issue.

**Comment by skavanagh** [comment]
You can try turning up the debug level on the SSH via CLI

ssh -vvv userid@ipaddress

**Comment by baggar11** [comment]
Here's what I'm getting. Every 60 seconds, a new set of last two lines prints to the terminal.

```
(Aerohive-switch) #logout

The system has unsaved changes.
Would you like to save them now? (y/n) n
debug3: receive packet: type 96
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug3: send packet: type 80
debug3: receive packet: type 82
debug3: send packet: type 80
debug3: receive packet: type 82
debug3: send packet: type 80
debug3: receive packet: type 82
debug3: send packet: type 80
debug3: receive packet: type 82
debug3: send packet: type 80
debug3: receive packet: type 82
debug3: send packet: type 80
debug3: receive packet: type 82
```

**Comment by skavanagh** [comment]
Do you think it could be an MTU mismatch?

http://www.snailbook.com/faq/mtu-mismatch.auto.html
