### ISSUE TITLE
Session already being invalidated

### ISSUE THREAD

**Issue by arbaiti** [skavanagh/KeyBox#262]
Hello,
First thanks for this solution.
I had two issues when testing KeyBox, 1st I have added the script under rc.local to start it at machine startup, but when i reboot the machine the script run well but when i log into Keybox the login page keep opening and i have this on the LOG (no logout was done before the reboot) ::
 2017-07-14 15:02:13.295:INFO:oejs.session:qtp654845766-14: Session node0zspbdlldj2n65dp2cdsimylm0 already being invalidated

2nd issue is the portal logout, i've extended the sessionTimeout to 120min but the portal logout after 10 min.
Best Regards,

**Comment by skavanagh** [comment]
Not sure how your startup script could be causing that. Here is documentation on how to enable jetty as a service.

https://www.eclipse.org/jetty/documentation/9.3.x/startup-unix-service.html

It honestly sounds like the CSRF token maybe causing the session to be invalidated.  Do you have user's logging in under the same account? That may be causing the 2nd issue too.

**Comment by arbaiti** [comment]
Thanks for your response.
No i have set multiple users, and i try to test with multiple login.
Normally i don't lose connection to the terminal but to the KeyBox Portal, and when i do an exit terminals, i got logged out from the Portal.

**Comment by skavanagh** [comment]
May need to rethink this,  but the session timeout corresponds to HTTP and not WebSockets. If you are doing things in the terminals it doesn't see it as an HTTP request and count it towards your timeout.

**Comment by arbaiti** [comment]
But the problem that we have is with session disconnection, when i got for 10min to do other tasks i find the login page for keyBox

**Comment by arbaiti** [comment]
2017-12-11 11:52:54,169 INFO  LoginAudit - xxxxxx (41.xxxxxx) - Authentication Success
2017-12-11 12:14:59.043:INFO:oejs.session:qtp707806938-12: Session node011hn3ti2j2shw1pm00zrlal63y0 already being invalidated
2017-12-11 12:18:04.637:INFO:oejs.session:qtp707806938-11: Session node05k12u468bj791voonvfjgjb5f1 already being invalidated
2017-12-11 12:18:22,832 INFO  LoginAudit - xxxxxxx (41.xxxxxxx) - Authentication Success

**Comment by skavanagh** [comment]
I haven't been able to recreate. Are you on 2.90.02?

**Comment by arbaiti** [comment]
Hi,
I'm  on v2.89_00

**Comment by skavanagh** [comment]
I know I was having issues the the CSRF token invaliding sessions with that version.  I think it's this commit that fixes https://github.com/skavanagh/KeyBox/commit/ea470fb26db75a1d23f369f7340b317b4e029a96

**Comment by arbaiti** [comment]
OK thanks for your reply, is there any way to upgrade this version but keeping the config and the info on the DB ?

**Comment by skavanagh** [comment]
You would need to run the "keybox-upgrade-2_90" upgrade to get to 2.90.02. I'm no longer putting the release and upgrade binaries out on github. You can either build the upgrade from source here: https://github.com/skavanagh/KeyBox-upgrade (there should be a release tagged with that version number). Or you can subscribe to get the binaries and upgrades: https://sshkeybox.com/subscription

**Comment by arbaiti** [comment]
OK thanks shavanagh
