### ISSUE TITLE
Terminals not loading / empty

### ISSUE THREAD

**Issue by alexschomb** [skavanagh/KeyBox#265]
Hi,

thanks for your great work on this project. Unfortunately I can't get the terminals to display anything, they are just empty black boxes. I did build from source with the latest release (v2.90.02) and tried the last available prebuilt jetty package that was available last week (before you removed them). Both versions don't work for me although KeyBox seems to successfully connect to the machines. What can I do to debug this issue? I tried several browsers and disabled all adblockers etc.

![alexschomb-mp 2017-12-17 um 16 04 17](https://user-images.githubusercontent.com/452417/34080854-b80baf58-e344-11e7-960d-273002d8949f.png)

![alexschomb-mp 2017-12-17 um 16 03 38](https://user-images.githubusercontent.com/452417/34080855-b829e6bc-e344-11e7-898c-97ddf55ceaf5.png)

**Comment by skavanagh** [comment]
That happens when websockets is being blocked - https://github.com/skavanagh/KeyBox/issues/132
