### ISSUE TITLE
Support for Ed25519 keys

### ISSUE THREAD

**Issue by Calyrx** [skavanagh/KeyBox#266]
Hello,

as with ecdsa it would be great if ED25519 could also be supported by the keybox.
ED25519 is considered to be a secure version of implementing elliptical curves. See also:
[https://wiki.archlinux.org/index.php/SSH_keys#Ed25519](https://wiki.archlinux.org/index.php/SSH_keys#Ed25519)

Best
Calyrx

**Comment by skavanagh** [comment]
I don't think ED25519 is supported by JSch, but you can use ECDSA and configure here 

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L7-L10

**Comment by Calyrx** [comment]
ok
