### ISSUE TITLE
Keybox with DMZ unsecured?

### ISSUE THREAD

**Issue by chrisarceo26** [skavanagh/KeyBox#268]
Can you please explain why Keybox is good with DMZ? Because as my perspective on the diagram on KEYBOX with DMZ its like unsecured for me. Please help me understand this. Thanks More power

**Comment by skavanagh** [comment]
When you allow SSH into a DMZ you can expose systems to the outside through tunneling / port forwarding.  By only allowing SSH through a bastion host over SSL you take that away.

https://www.sans.org/reading-room/whitepapers/vpns/security-implications-ssh-1180

**Comment by chrisarceo26** [comment]
That's Great. Thanks!
