### ISSUE TITLE
Composite Terms docker synology reverse proxy

### ISSUE THREAD

**Issue by zeuslooye** [skavanagh/KeyBox#273]
Hello
like Keybox very much but i have a small problem.

I have used the docker container to use key box (adito/keybox).
I run docker on my synology (a NAS) and i expose 443 to the outside on port 32702. I use the reverse proxy of synology to map a name to (https://keybox......) port 32702.
When I want to connect to a server the console window stays black and has a grey line in the middel. but when i connect to my synology IP on port 32702 the terminal wil display. 
can you point me in a direction where to look to get this working?

tnx 
Jeroen (dutch)

**Comment by skavanagh** [comment]
Sounds like the reverse-proxy isn't setup for websockets. Not sure what reverse-proxy synology runs (Nginx??) .. but there has been a couple of issues on here with some different setups https://github.com/skavanagh/KeyBox/issues/51 https://github.com/skavanagh/KeyBox/issues/181
