### ISSUE TITLE
How to use Ctrl keys in keybox terminal example nano editor

### ISSUE THREAD

**Issue by ferdousulhaque** [skavanagh/KeyBox#276]
I have been facing an issue regarding the use of nano editor in the keybox terminal. I am able to open a file using the nano editor, but when I am trying to Write Out using Ctrl+w, whole browser is closing up, not able to close the nano properly. Please let me know how to use the Ctrl keys in the Keybox for further steps.

Also how to close an daemon with Ctrl+c.

**Comment by skavanagh** [comment]
Ctrl-C  works fine! The Ctrl-W event typically won't make it to the application, before the browser acts on it. https://github.com/skavanagh/KeyBox/issues/104
