### ISSUE TITLE
Umlaute/special chars messed up after upgrade

### ISSUE THREAD

**Issue by taenzerme** [skavanagh/KeyBox#278]
Hey all,

after upgrading to Keybox 3 (the paid one with Jetty included) all our special chars and umlauts are broken in the UI. Keybox is running behind nginx using proxy_pass.

![screenshot 2018-06-08 16 56 43](https://user-images.githubusercontent.com/3618912/41165094-09fdb754-6b3d-11e8-81ad-5ee78bdde681.png)

Any ideas?

Kind regards
Sebastian

**Comment by skavanagh** [comment]
https://github.com/skavanagh/lmvc/commit/e6fb77255ba16f3e3d1530b1d7556294ff673eb7 - should fix
