### ISSUE TITLE
DB-ERROR

### ISSUE THREAD

**Issue by abhinav193** [skavanagh/KeyBox#281]
ERROR DBUtils - java.sql.SQLException: Cannot create PoolableConnectionFactory (General error: "java.lang.NoSuchMethodError: java.lang.invoke.MethodHandles.byteArrayViewVarHandle(Ljava/lang/Class;Ljava/nio/ByteOrder;)Ljava/lang/invoke/VarHandle;" [50000-197])
getting above error while running mvn package jetty:run

**Comment by abhinav193** [comment]
[db_error.txt](https://github.com/skavanagh/KeyBox/files/2302288/db_error.txt)

**Comment by skavanagh** [comment]
What version of Java are you on?  You need to be on JDK 9 or greater.

**Comment by abhinav193** [comment]
using jdk9

**Comment by abhinav193** [comment]
any update on above please 
getting illegalstate exception stating that General error: "java.lang.IllegalStateException: The file is locked: nio:/home/ubuntu/KeyBox/target/classes/keydb/keybox.mv.db [1.4.197/7]" [50000-197]
![image](https://user-images.githubusercontent.com/39628092/44344130-8441c380-a4ad-11e8-9b63-22e80b26f82e.png)

**Comment by abhinav193** [comment]
Please provide an update on above errors. It would be helpful to me if you respond on them asap.

**Comment by skavanagh** [comment]
Excuse me.... but first of all I don’t owe you support for free. 

Also, you are building off of a snapshot release, which maybe unstable as I’m testing the jetty release candidate.  You can find actual releases tagged here. 

https://github.com/skavanagh/KeyBox/releases
