### ISSUE TITLE
Empty Terminal

### ISSUE THREAD

**Issue by philippkayser** [skavanagh/KeyBox#282]
I’m using Keybox on Ubuntu 18.04.1.

Since a few days, the web interface will not open the terminals completely and I cannot find anything in logs.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/41049458/45281342-d76ccc00-b4d7-11e8-8770-29e59aa7e596.png">

`
[INFO] Configuring Jetty from xml configuration file = /root/KeyBox-3.01.00/src/test/resources/jetty-ssl.xml
[INFO] Configuring Jetty from xml configuration file = /root/KeyBox-3.01.00/src/test/resources/jetty-https.xml
[INFO] Context path = /
[INFO] Tmp directory = /root/KeyBox-3.01.00/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:///root/KeyBox-3.01.00/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /root/KeyBox-3.01.00/src/main/webapp
[INFO] jetty-9.4.11.v20180605; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 10.0.2+13
[WARNING] Unknown asm implementation version, assuming version 393216
[WARNING] com.jcraft.jsch.jce.SignatureECDSA scanned from multiple locations: file:///root/KeyBox-3.01.00/target/classes/com/jcraft/jsch/jce/SignatureECDSA.class, jar:file:///root/.m2/repository/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar!/com/jcraft/jsch/jce/SignatureECDSA.class
[INFO] Scanning elapsed time=466ms
[INFO] DefaultSessionIdManager workerName=node0
[INFO] No SessionScavenger set, using defaults
[INFO] node0 Scavenging every 600000ms
[INFO] Started o.e.j.m.p.JettyWebAppContext@54ccb3{/,file:///root/KeyBox-3.01.00/src/main/webapp/,AVAILABLE}{file:///root/KeyBox-3.01.00/src/main/webapp/}
[INFO] x509=X509@408f70ab(jetty,h=[],w=[]) for SslContextFactory@5383bf08[provider=null,keyStore=file:///root/KeyBox-3.01.00/src/test/resources/keystore,trustStore=null]
[INFO] Started ServerConnector@4cbaf213{SSL,[ssl, http/1.1]}{0.0.0.0:443}
[INFO] Started @7305ms
[INFO] Started Jetty Server
                [LdapLoginModule] search-first mode; SSL disabled
                [LdapLoginModule] user provider: ldap://rz-dc01......:389/DC=domain,DC=de
                [LdapLoginModule] searching for entry belonging to user: admin
                [LdapLoginModule] authentication failed
                [LdapLoginModule] aborted authentication
2018-09-10 06:41:52,304 INFO  LoginAudit - admin (192.168.1.20) - Authentication Success
                [LdapLoginModule] search-first mode; SSL disabled
                [LdapLoginModule] user provider: ldap://rz-dc01......:389/DC=domain,DC=de
                [LdapLoginModule] searching for entry belonging to user: admin
                [LdapLoginModule] authentication failed
                [LdapLoginModule] aborted authentication
2018-09-10 06:53:25,801 INFO  LoginAudit - admin (192.168.1.20) - Authentication Success`

**Comment by skavanagh** [comment]
Websockets is being blocked - https://github.com/skavanagh/KeyBox/issues/265

You should see an error in your browser's javascript console.  I see this a lot by users who run keybox behind a reverse-proxy or firewall.

**Comment by philippkayser** [comment]
Hi,

I’ve answered to the corresponding ticket, but its currently closed.

https://github.com/skavanagh/KeyBox/issues/51#issuecomment-429744767 <https://github.com/skavanagh/KeyBox/issues/51#issuecomment-429744767>


Gruß/Regards


Philipp Kayser

**Comment by philippkayser** [comment]
Now I’ve fixed it.

Gruß/Regards


Philipp Kayser
