### ISSUE TITLE
KeyBox not accepting some passwords

### ISSUE THREAD

**Issue by neilwhitespace** [skavanagh/KeyBox#287]
The password validation for KeyBox does not appear to be working as stated:

> Passwords must be 8 to 20 characters, contain one digit, one lowercase, one uppercase, and one special character

Here's a sample of passwords it did not accept:

```
QJvaoWB}3ZkTF
M9PpEvgo;EaLq
Wa3p}GpcmHToj
NJPi;jmMCQ8uC
```

And a sample password that it did accept:

```
qykaMEN3wMEce!
```

Can you please either further clarify the password requirements within the interface or consider fixing the validation if it's broken? Thanks!

**Comment by skavanagh** [comment]
This is actually configurable 

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L35-L38

.. but I'll add more special chars to the default

**Comment by neilwhitespace** [comment]
Ah, interesting - I guess the default just needs a bit of love then, but good to know we can change this ourselves. Thanks!

I'll let you take the call on closing this one ;)

**Comment by neilwhitespace** [comment]
For your reference, @skavanagh I changed the special character portion of the regex to use `\W` instead of `[!@#$%^&*()+=]`.

**Comment by skavanagh** [comment]
Added more chars to the regex.  Not sure about `\W` since it will match spaces and symbols.
