### ISSUE TITLE
Migration process from 2.85.03

### ISSUE THREAD

**Issue by tswestendorp** [skavanagh/KeyBox#293]
Is there some kinds of workflow available to upgrade from 2.85.03

Tried several things already, but the furthest I can is having Keybox running but being unable to login with an error saying "Uh oh... Something went wrong!"

**Comment by skavanagh** [comment]
1. Backup the previous version

mv KeyBox-jetty keybox-backup

2. Download and Untar 3.02
https://github.com/bastillion-io/Bastillion/releases/download/v3.05.01/bastillion-jetty-v3.05_01.tar.gz

tar xfz bastillion-jetty-v3.05_01.tar.gz

3. Copy over the previous database 

cp -R keybox-backup/jetty/keybox/WEB-INF/classes/keydb KeyBox-jetty/jetty/keybox/WEB-INF/classes/

4. Run the 2.87 upgrade jar - https://s3.amazonaws.com/keybox-archive/3kd8dl/keybox/v2.87.00/keybox-upgrade-2_87.jar

java -jar keybox-upgrade-2_87.jar /opt/KeyBox-jetty/jetty/keybox/WEB-INF/classes/keydb/keybox.h2.db

5. Run the 2.89 upgrade jar - https://s3.amazonaws.com/keybox-archive/3kd8dl/keybox/v2.89.00/keybox-upgrade-2_89.jar

java -jar keybox-upgrade-2_89.jar /opt/KeyBox-jetty/jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties

If there is too much data in the audit table and the upgrade doesn't complete, you may want to think about running a trunc first or using this jar to do the 2.89 upgrade

https://s3.amazonaws.com/keybox-archive/3kd8dl/keybox/v2.89.00/keybox-upgrade-truncate-2_89.jar

6. Run the 2.90 upgrade jar - https://s3.amazonaws.com/keybox-archive/3kd8dl/keybox/v2.90.00/keybox-upgrade-2_90.jar

java -jar keybox-upgrade-2_90.jar /opt/KeyBox-jetty/jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties

7. Rename KeyBoxConfig.properties to BastillionConfig.properties and rename keybox.jceks to bastillion.jceks

8. Run the 3.06 upgrade jar

java -jar bastillion-upgrade-3.06.00.jar <whatever path>/jetty/bastillion/WEB-INF/classes/BastillionConfig.properties

9. Any other custom settings in the BastillionConfig.properties, jaas.conf, or the log4j2.xml need to be added to the new install

**Comment by tswestendorp** [comment]
Thank you for the explanation! 

I'm getting some errors related to missing tables (session_log, terminal_log, users) in step 5, is this problematic? The run completes with 'upgrade successful' though.
