### ISSUE TITLE
Bastillion always overwrite my .ssh/authorized_keys

### ISSUE THREAD

**Issue by ericxuo** [skavanagh/KeyBox#318]
Hi,

I've installed bastillio-jetty 3.06.04
I've modified the file jetty/bastillion/WEB-INF/classes/BastillionConfig.properties to set : 
forceUserKeyGeneration=false

Then I've restarted Bastillion and start it again.
But Bastillion continues to overwrite my .ssh/authorized_keys with its certificate and removes the others.
Do you know what I can do to solve this issue ?

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

You're right. I didn't modify the correct variable. Sorry for the waste of time.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

I'm back on this topic as the .ssh/authorized_keys is still overwritten by Bastillion's keys.
The variable keyManagementEnabled in the file Bastillion-jetty/jetty/bastillion/WEB-INF/classes/BastillionConfig.properties is set to false.

Is there anything I should recompile ? Or is this variable used only under certain use cases ?

I've set the variable :
authKeysRefreshInterval=0
to see if it changes anything in Bastillion's behaviour.

Regards.

Xuo.

**Comment by chinnayya995** [comment]
Hi,

I've installed bastillio-jetty 3.10.00

Bastillion continues to overwrite my .ssh/authorized_keys with its certificate and removes the others.
Do you know what I can do to solve this issue ?

Regards.
