### ISSUE TITLE
Moving KeyBox installation to a new server

### ISSUE THREAD

**Issue by johnwards** [skavanagh/KeyBox#4]
I'd like to move my Keybox installation from my Mac to a dedicated Linux server.

I was hoping to just tar up the folder and run it on the new server, but sadly that is erroring.

I can get keybox to run fine on the new server, and it runs without errors on my mac, I just can't seem to get my tar'ed version running.

What is the simplest process to move my existing data from one setup to another?

**Comment by tvb** [comment]
the correct location is:

`jetty/keybox/WEB-INF/classes/keydb/keybox.h2.db`
