### ISSUE TITLE
Feature request: User / PW support for initial host setup

### ISSUE THREAD

**Issue by nox-do** [skavanagh/KeyBox#41]
In some cases the keybox key is NOT the key we've used during provisioning. So I'd like to see an option to open the first time connection via username/password if no key has been applied to a host by keybox before.

I'd not offer this function for users at all. Keys are preferred. But it would help to set up the hosts for keybox use. 

From a discussion with skavenagh:
"When you add a host it should prompt your for username and password if the key is not set.  And you should be able to set a custom key for keybox to use by doing."

So I leave this open for discussion. - Thanks for additional ideas.

**Comment by skavanagh** [comment]
Currently when keybox first starts up it generates a keypair or you can define a custom keypair by doing 

https://github.com/skavanagh/KeyBox#supplying-a-custom-ssh-key-pair

When you first add a system it should prompt for a user name and password, then set it's public key.

![password_prompt](https://cloud.githubusercontent.com/assets/3192731/5970252/7901e018-a7fe-11e4-8bf3-d503b9c3331e.png)

Do you maybe have password authentication disabled on the host systems you are adding??
```
/etc/ssh/sshd_config
PasswordAuthentication no
```
If it is then there is no other option then to provision the systems with the keybox generated key (or you have set for it)
