### ISSUE TITLE
Disable SSL/TLS?

### ISSUE THREAD

**Issue by ekollof** [skavanagh/KeyBox#51]
Can SSL/TLS be disabled? Because my nginx already terminates SSL.

**Comment by skavanagh** [comment]
in the jetty directory edit the start.ini file

change

--module=https

to

--module=http

and change jetty.port=8443

to whatever you need it to be and restart.

**Comment by ekollof** [comment]
Awesome, thanks!

**Comment by skavanagh** [comment]
No problem.  Glad it helped! :metal:

**Comment by yves-ledermann** [comment]
@ekollof 
sorry to ask but can you tell me how to configure nginx as reverse proxy to keybox?
I have problems to get the websockets working...

**Comment by rgv151** [comment]
```
location / {
                proxy_pass https://localhost:8443/;
                proxy_read_timeout 1800s;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }
```
Above snippet is my Nginx proxy config for Keybox,  no need to disable ssl .

Note: Nginx proxy timeout  is 60s by default, websocket will be terminated after that. increase `proxy_read_timeout` parameter as your need

**Comment by yves-ledermann** [comment]
@rgv151 
Thank you verry much. Its working after i updated nginx to 1.6.2 (the debian wheezy nginx V1.2 does not support ws) and applied your config snippet...

**Comment by ausip** [comment]
I am also having trouble getting Keybox to work from behind an Nginx reverse proxy. I can access it via the local lan on the configured HTTP port of 8080, but when trying to access it from external via nginx, nginx is returning a 502 Bad Gateway error.

Any ideas?

**Comment by ausip** [comment]
I worked out my 502 Bad Gateway Error. It was pesky SELinux on the nginx box. Putting SELinux into permissive mode fixed the issue.

**Comment by skavanagh** [comment]
@ausip - Thanks for posting the fix!

**Comment by ekollof** [comment]
Putting SELinux in permissive mode is *not* a fix.

**Comment by skavanagh** [comment]
@ekollof - Yeah good point!

**Comment by giopas** [comment]
Hi,

has anyone made KeyBox working with an Apache reverse proxy?

I currently have the following VirtualHost set, but I have a visual glitch on the terminal.

As Sean told me, it is very likely that this is caused by the reverse-proxy blocking web sockets:

    <VirtualHost *:80>
       ServerName sub.domain.com
       ProxyRequests Off
    <Proxy *>
       Order deny,allow
       Allow from all
    </Proxy>
    <Location />
       Order allow,deny
       Allow from all
    </Location>
       ProxyPass / http://localhost:58000/
       ProxyPreserveHost On
       ProxyStatus On
    </VirtualHost>

I have tried with the below, but maybe I would need some advice on how to use them as I cannot get rid of the problem:

1)

    ProxyPass "/" "ws://localhost:58000/"
    ProxyPass "/" "wss://localhost:58000/"

2)

    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^/ [NC]
    RewriteCond %{QUERY_STRING} transport=websocket [NC]
    RewriteRule /(.*) ws://localhost:58000/$1 [P,L]

Thank you

**Comment by colandre** [comment]
I have a working configuration.
Here below the full VirtualHost configuration I have:
    <VirtualHost *:443>
      ServerName example.com    

      ## Logging
      ErrorLog "/var/log/httpd/example_error_ssl.log"
      ServerSignature Off
      CustomLog "/var/log/httpd/example_access_ssl.log" combined    
    

     ## SSL directives
      SSLEngine on
      SSLProxyEngine On
      SSLProxyCheckPeerCN off
      SSLProxyCheckPeerName off
      SSLProxyVerify none
      SSLProxyCheckPeerExpire off    

      SSLCertificateFile      "/etc/ssl/mycert.crt"
      SSLCertificateKeyFile   "/etc/ssl/mykey.key"
      SSLCACertificatePath    "/etc/pki/tls/certs"    

      ## Proxy rules
      ProxyRequests off
      ProxyPreserveHost On
      ProxyPass / https://localhost:8443/
      ProxyPassReverse / https://localhost:8443/    

      <LocationMatch "/admin/(terms.*)">
            ProxyPass wss://127.0.0.1:8443/admin/$1
            ProxyPassReverse wss://127.0.0.1:8443/admin/$1
      </LocationMatch>    

      RequestHeader set X-Forwarded-Proto "https" env=HTTPS    

    </VirtualHost>

Jetty is running on port 8443 in https. I had problem with httpd 2.4.6 (last httpd updated when I tried on CentOS) in regard with an apache bug with web sockets. I had to install httpd 2.4.10.
[Apache Bug Ref](https://bz.apache.org/bugzilla/show_bug.cgi?id=55320)

I hope this helps

**Comment by giopas** [comment]
Hi colandre,

thanks for your reply.

I have modified the VirtualHost section as follows:

    <VirtualHost *:80>
        ServerName sub.domain.com
        ProxyRequests Off
    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>
    <LocationMatch "/admin/(terms.*)">
        ProxyPass ws://127.0.0.1:58000/$1
        ProxyPassReverse ws://127.0.0.1:58000/$1
    </LocationMatch>
        ProxyPass / http://localhost:58000/
        ProxyPassReverse / http://localhost:58000/
        ProxyRequests Off
        ProxyPreserveHost On
        ProxyStatus On
    </VirtualHost>[/code]

However I still have the same problem which may be related to the but you are mentioning. A simple question: how can I check which httpd am I running (on a NAS everything is more difficult) :)

**Comment by colandre** [comment]
One thing that I find wrong in your configuration is the ws:// URI in the location match. You wrote:
    <LocationMatch "/admin/(terms.*)">
        ProxyPass ws://127.0.0.1:58000/$1
        ProxyPassReverse ws://127.0.0.1:58000/$1
    </LocationMatch>

You are missing /admin. I think it should be:
    <LocationMatch "/admin/(terms.*)">
        ProxyPass ws://127.0.0.1:58000/admin/$1
        ProxyPassReverse ws://127.0.0.1:58000/admin/$1
    </LocationMatch>

**Comment by giopas** [comment]
Grazie colandre,

I did modify it, but it did not solve the problem.

I actually found another, much worst problem: as far as I understood [1] to use mod_proxy_wstunnel extention of mod_proxy you need to run Apache > 2.4.5 but I am currently running Apache 2.2.31 on my QNAP.

I would therefore need to upgrade or patch Apache to use it [2].

Do you think this could indeed be the problem?

[1] http://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html
[2] http://stackoverflow.com/questions/30443999/how-to-add-mod-proxy-wstunnel-to-apache2-2-2-on-raspberry-pi-backport-mod-proxy

**Comment by colandre** [comment]
I do not think that Apache 2.2.31 is the problem. I have found backporting and patches for mod_proxy_wstunnel for Apache 2.2.20, but I really don't know if your version is working.

It should be good to upgrade at least to Apache version 2.4.10 or greater.

**Comment by giopas** [comment]
sure, the problem is that such Apache version is running on a QNAP and I cannot patch it myself. I hope their support team can assist me on this. In any case, thank you for your support and advise!

**Comment by philippkayser** [comment]
Hi guys,

I'm using apache as reverse proxy and don't get it to work correct.

`<VirtualHost *:443>

ServerName ssh.domain.de
ServerAlias ssh
ServerAdmin root@localhost.local

    SSLProxyEngine On
    ProxyPass / https://192.168.100.6/
    ProxyPassReverse / https://192.168.100.6/
    <LocationMatch "/admin/(terms.*)">
        ProxyPass ws://192.168.100.6/admin/$1
        ProxyPassReverse ws://192.168.100.6/admin/$1
    </LocationMatch>
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyStatus On


    SSLEngine off
SSLCertificateFile /etc/letsencrypt/live/ssh.domain.de/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/ssh.domain.de/privkey.pem
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

</VirtualHost>`

**Comment by philippkayser** [comment]
I've fixed it now. The second config from my last post was correct but i've forgot to enable apache proxy_wstunnel module with "a2enmod proxy_wstunnel"

Thanks!

**Comment by Nutties93** [comment]
I am using nginx as reverse proxy, but sometimes I'm getting a 502 gateway error to my bastillion using hostname. However, when i try to access bastillion using the <ip>:<port> i was able to access the bastillion login page. Anybody faced this issue before?
