### ISSUE TITLE
Change terminal colors? 

### ISSUE THREAD

**Issue by ekollof** [skavanagh/KeyBox#52]
It would be nice to have dark backgrounds and light text. Or at least have that configurable according to taste. It also has a practical use. You could for instance have different colors depending on machines for production and development.

**Comment by skavanagh** [comment]
Yeah, that would be really nice to be able to configure in the app

You can change the to a dark background by editing
https://github.com/skavanagh/KeyBox/blob/master/src/main/webapp/_res/js/tty/term.js#L357-L361
comment out lines 358 - 359 and uncomment 340 - 341.  You may have to fix up some css too.

Also, you could change

https://github.com/skavanagh/KeyBox/blob/master/src/main/webapp/admin/secure_shell.jsp#L250-L256

to pass in the colors like so

```
termMap[id] = new Terminal({
        cols: Math.floor($('.output:first').innerWidth()/7.2981), rows: 24,
        screenKeys: false,
        useStyle: true,
        cursorBlink: true,
        convertEol: true,
        colors: [
                '#000000',
                '#cd0000',
                '#00cd00',
                '#cdcd00',
                '#0000ee',
                '#cd00cd',
                '#00cdcd',
                '#e5e5e5',
                '#7f7f7f',
                '#ff0000',
                '#00ff00',
                '#ffff00',
                '#5c5cff',
                '#ff00ff',
                '#00ffff',
                '#ffffff',
                '#ffffff',
                '#000000'
        ]
 });
```

**Comment by ekollof** [comment]
Thanks, I'll give it a burl.
