### ISSUE TITLE
Space button is deleting characters on the terminal prompt

### ISSUE THREAD

**Issue by yharsh** [skavanagh/KeyBox#58]
There is one issue related to space character. Pressing space is deleting character on the left of first user inserted space.

How to reproduce:

Let character '|' denotes current cursor position.

yharsh@github>Hi my name is harsh|
yharsh@github>Hi my na |me is harsh -----> First space is inserted between characters 'a' and 'm' of word "name"
Now position the cursor to the left of this space and press space. Say I position cursor next to 'n' and press space button. Now it will delete characters 'a' and ' ', 'm', 'e' and so on on consecutive press.
yharsh@github>Hi my n|a me is harsh ------> Cursor is next to 'n'.
Press space button
yharsh@github>Hi my n | me is harsh -------> Space character has overwritten character 'a'.
Press space button
yharsh@github>Hi my n |me is harsh -------> Space character has overwritten character ' '.
Press space button
yharsh@github>Hi my n e is harsh -------> Space character has overwritten character 'm'.

Any help/fix in this regards is much appreciated.

Thanks
Harsh Yadav

**Comment by skavanagh** [comment]
I can't reproduce this! Could be an issue with the shell you are connect maybe with the term settings.

I saw this issue a couple weeks back on the term.js project.  I using that library but I'm mapping the little different.

https://github.com/skavanagh/KeyBox/blob/master/src/main/java/com/keybox/manage/socket/SecureShellWS.java#L161

Not sure how to help!

**Comment by yharsh** [comment]
Thanks for pointing in right direction. I was using 'vt102' instead of 'xterm' as terminal type while creating ssh connection.
