### ISSUE TITLE
SSH Terminal is not resizable 

### ISSUE THREAD

**Issue by malafeev** [skavanagh/KeyBox#6]
Cannot change size of created ssh terminal.

**Comment by nerdev** [comment]
I would first like to say thank you for the great piece of software! Keybox has solved many of my problems very quickly and easily. But like the other people that have posted here, I too would love to see a resizing feature. I didn't want to post here just to clutter up the thread, but more to show you that there are more people that want this. Thanks again for all of your work!

**Comment by skavanagh** [comment]
Thanks @nerdev! I have been working on this. I'll commit what I have tonight.  I may wait before tagging and doing a release though, so you'll have to build from source.
