### ISSUE TITLE
Duplicate Session

### ISSUE THREAD

**Issue by rmkjr** [skavanagh/KeyBox#61]
I was thinking an awesome feature add would be some way to "duplicate" a session from within the composite terms screen.
Basically the "Duplicate Session" functionality from putty.
Either a button at the top of each shell window, or a drag and drop area like the disconnect option.
When that button is pressed or a shell is is dragged to that area, another shell to the same machine with the same credentials should be created as a new shell window.  Having the ability to have multiple sessions open to the same machine is super useful when doing things like comparing configurations or maybe running an app in one and modifying files in another during development.

**Comment by sibivk** [comment]
I concur +1

**Comment by skavanagh** [comment]
+1 I've had a couple ppl ask about for this. Something I wish I would have thought about in the beginning.  It's going to change how sessions are mapped on the backend, but I think it's doable.
