### ISSUE TITLE
Password Complexity does not meet all policies

### ISSUE THREAD

**Issue by jannemann** [skavanagh/KeyBox#64]
Please make the password policy configurable. e.g. set what character types are have to be included, minimum length, forbidden words or parts (name, word list) ...

just for the background story. we moving away from complex passwords to easy to remember and even more secure ones.

https://xkcd.com/936/

**Comment by skavanagh** [comment]
+1

**Comment by skavanagh** [comment]
I made the Regex configurable in the KeyBox.properties.  I like the idea of a dictionary check and there maybe libraries out there that can help with that (so I'll leave this issue open).

**Comment by jannemann** [comment]
Thanks, thats nice. I gonna check out some libraries later.
