### ISSUE TITLE
Home/End/PgUp/PgDown keys not mapped?

### ISSUE THREAD

**Issue by simongormley** [skavanagh/KeyBox#68]
Hi,

When I'm in a terminal window and press Home or End, I'd expect to move to the start or end of the line, but instead I get a character "$" or "#" output - is it possible to have the Home and End keys work as a local terminal?

Page up and down also do something similar.

I've tried this using 2.82, and Firefox 31.6

**Comment by skavanagh** [comment]
This should get it - Thanks!!

**Comment by simongormley** [comment]
Awesome, works great now, thanks!!
