### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by nox-do** [skavanagh/KeyBox#69]
I've recognized that the German Keyboard Layout is not properly supported. Most keys work but not the keys that require German users to press AltGr + the Key: like: [,],@~} . I'm sure other keyboard layouts are effected too. But who is brave enough to try a french keyboard :-)

Any idea how this could be solved? Thank your Sean.

**Comment by skavanagh** [comment]
Looks like you can trap it by checking for ctrl and alt. http://stackoverflow.com/a/18570096
Just a stab at it!! And I don't really have a way to check, but hopefully it will work. - Thanks!
