### ISSUE TITLE
Common Key Pair for All Accounts

### ISSUE THREAD

**Issue by vjl518** [skavanagh/KeyBox#73]
First, I am new to KeyBox, so I may not be doing everything perfect just yet.

For my install I have started it using a custom key pair, which works fine. This key is present on existing systems and I am able to create the initial connections as expected.

Since password authentication is disabled on my systems it seems I am required to leverage the custom key pair I started KeyBox with for every system account I want to be able to connect to. Is there a way to provide a secondary key pair to enable this first connection?

For instance, when I setup the system it would be nice if I could also provide the appropriate keys to enable the initial connection to the host for the account being used. This assumes the public key is already on the host within the users authorized_keys file, but I can handle that in my automation.

**Comment by skavanagh** [comment]
No there isn't and it will only ever store/use one private key.

When KeyBox first starts up it generates a pub/pvt key pair (or you can set
a custom), encrypts it, and stores in it's DB.  It uses that one private
key for everything, so if password authentication is turned off, you will
have to provision the public key it uses on the systems prior to setting
them in the application.

The key that is generated (or set) above is used whenever a user connects
in the web-shell (even if they have their own keys set).

When user a sets their own key on a system and downloads the private (so
they can connect directly without KeyBox), it doesn't store that private
key anywhere.  It only keeps the public when managing user's keys.

**Comment by vjl518** [comment]
Thanks, that answers my question.
