### ISSUE TITLE
Custom user keys not working

### ISSUE THREAD

**Issue by vjl518** [skavanagh/KeyBox#74]
After my initial setup leveraging a custom key pair, I have been able to create new user keys within the application and have them propagated to the appropriate systems. 

However, if I remove the custom key (used to start KeyBox) from the system/account’s authorized_key file the user is not able to connect the system. The secondary keys I created within the application for the user continues to exist in the system account authorized_key file, but the user is unable to connect from the UI. Is this intended functionality or do I potentially have something setup incorrectly?

**Comment by skavanagh** [comment]
see https://github.com/skavanagh/KeyBox/issues/73#issuecomment-95217875
