### ISSUE TITLE
Add the ability for multiple users to collaborate on a session?

### ISSUE THREAD

**Issue by InfoSec812** [skavanagh/KeyBox#75]
For training and support purposes, it would be ideal for 2 (or more) users to share a single shell session using KeyBox. I have often started on a similar project to implement said functionality, but never quite had the time to really get it done. Perhaps I could assist in developing that functionality for KeyBox?

**Comment by skavanagh** [comment]
I think this would be tough!! - The io streams from the SSH connections to the hosts are mapped to a the user's session. Making that (and the data going to and from it) available to multiple sessions would be difficult.  Also, what if User B doesn't have permission to a host that User A wants to share?

**Comment by InfoSec812** [comment]
Do I have a tool to show you! http://vert-x3.github.io/ The reactive streams in Vert.x make it really simple to send messages to/from the browser. It also has clustered sessions which make it really scalable.

**Comment by nox-do** [comment]
wouldn't be the tool screen be ideal for you? it helped me for that purpose
for decades now. actually it allows you to detach a console but more than
one person than can attach to the same "screen" at the same time.
Am 06.05.2015 02:09 schrieb "Deven Phillips" <notifications@github.com>:

**Comment by InfoSec812** [comment]
"screen" is a nice tool, but you have to ensure it is installed, configure it SUID, enable multiuser for each session, and you have to worry about the other user being able to determine the "screen" session ID. Having something like KeyBox, which is web based and has auditing, could make for a MUCH better solution. With a centrally controlled application, you could audit back to an individual user to determine who typed which commands. You could also enable teams to do cross-training by sharing sessions while doing various procedures... Need to teach a remote colleague how to configure IPTables? Fire up a shared session on KeyBox and show them how.

Here's what I envisioned when I originally thought of a tool like this:

1. The "owner" of a session could invite another user and the session would use the permissions assigned to the "owner".
2. The "owner" can grant/revoke access for the invited user at any time. This could include 2 options. Disable the invited user from typing or kick the user out of the shared session. Additionally, you don't want 2 people trying to type at the same time, so control of the session is limited to a single user at a time, with the owner able to wrest control whenever they felt the need.
3. There could be an associated "chat" area on the page which could allow the participants to share commands or discuss the work being done.
4. There could be a "training" mode for invited participants where the "ENTER" key is caught and requires the approval of the "owner" before a command could be submitted.
5. There would be some sort of indication of which users are currently attached to the session and their current status (connected, in control, training)

That's a lot of stuff, but it would be a killer set of features for large enterprises!

**Comment by skavanagh** [comment]
I'm interested in using keybox in ways to enhance security for an enterprise.  It's a neat idea, but it doesn't follow that theme.
