### ISSUE TITLE
"Settings" section not displayed for LDAP users

### ISSUE THREAD

**Issue by InfoSec812** [skavanagh/KeyBox#76]
I have set up AD LDAP authentication for KeyBox, and it works for authentication. The problem is that the "Settings" area is not linked anywhere in the UI when I log in with an AD/LDAP user. When I create a "Basic" user and give them full access, the option is displayed.

**Comment by skavanagh** [comment]
Yeah that screen used to only just have "Change Password" (which doesn't apply for AD/LDAP users) . but now that themes are there, it just show those settings for AD/LDAP users now. Thank you!!

**Comment by InfoSec812** [comment]
Awesome! Thanks for the quick fix!
