### ISSUE TITLE
Terminals opened to same host instead of different hosts

### ISSUE THREAD

**Issue by simongormley** [skavanagh/KeyBox#77]
Occasionally, when opening multiple terminals at the same time, instead of opening terminals to host 1, 2 and 3, there are 3 windows opened up, with the titles as expected (host 1, host2, host 3), but the terminals are actually all connected to host 1, as confirmed by the bash prompt and running hostname -i.

This problem is intermittent, so presumably some sort of timing issue. 

Any idea what could be causing it? There were no errors in the output.

**Comment by simongormley** [comment]
oops - user error! Please ignore me... :-)

**Comment by skavanagh** [comment]
No problem!  - was worried the ajax calls where going async. I've had issues like that before where I've had to make sure and call  $.ajaxSetup({async: false});

Thanks Simon!
