### ISSUE TITLE
authorized_keys file with wrong permissions

### ISSUE THREAD

**Issue by Busindre** [skavanagh/KeyBox#78]
If no authorized_keys file on the system, Keybox creates the authorized_keys file with wrong privileges in some distributions when a user is used without root privileges (if the password is used to access from keybox) . 

$ ls -lt .ssh/authorized_keys
-rw-rw-r-- 1 caca caca 3610 18. Mai 15:51 .ssh/authorized_keys

SSH Logs (/var/log/secure)
May 18 15:57:54 popoch sshd[18943]: Authentication refused: bad ownership or modes for file /home/caca/.ssh/authorized_keys

The file permissions should be 600 (-rw-------). Keybox should force the use of the correct permissions

**Comment by skavanagh** [comment]
Nice catch - Thanks!
