### ISSUE TITLE
Auth Cancel

### ISSUE THREAD

**Issue by pshanmu** [skavanagh/KeyBox#79]
I just installed KeyBox (FirstTime)

When start adding systems with root user and I have given correct root password.  KeyBox throws "Error: Auth cancel"

Please suggest me

- Shanmu

![keybox-auth-error](https://cloud.githubusercontent.com/assets/12595709/7797009/f00a3894-0303-11e5-82e1-4a0fcde64775.png)

**Comment by skavanagh** [comment]
Did you use a custom SSH key pair or have KeyBox generate one for you??

Also, you may want to check the /etc/ssh/sshd_config on the host you are trying to connect to and make sure it doesn't have anything set that would prevent authentication.
Like for example..
```
PermitRootLogin no
```

**Comment by pshanmu** [comment]
Hi,

thanks for your quick response.

I did not use Custom SSH Key , I did not generate any also  (sorry if  have
missed anything)


Root login is allowed (i am able to do manual SSH)

#LoginGraceTime 2m

PermitRootLogin yes


- Shanmu

**Comment by skavanagh** [comment]
The public key (id_rsa.pub) that it is using to try and connect should be in the jetty/keybox/WEB-INF/classes/keydb

You could try and put it in the authorized_keys file on the host and try and register the host again.

**Comment by pshanmu** [comment]
Yes. I could see the key id_rsa.pub generated by KeyBox in
 jetty/keybox/WEB-INF/classes/keydb.


   1. Should I have to put this key in authorized_keys file ?
   2. where the authorized_keys file is ? (local or remote) ?


Sorry - if I am asking some basic queries!

- Shanmu

**Comment by pshanmu** [comment]
root@mgmt1:~ # ls -la .ssh/

total 12

drwx------  2 root  wheel   512 May 12 11:01 .

drwxr-xr-x  3 root  wheel   512 May 25 13:30 ..

-rw-r--r--  1 root  wheel  3062 May 18 12:59 known_hosts

root@mgmt1:~ #

root@mgmt1:~ #

root@mgmt1:~ #


This is list of files in KeyBox Server - Please note I am using FreeBSD


- shanmu

**Comment by skavanagh** [comment]
> 1. Should I have to put this key in authorized_keys file ?

No, it should do it for you when adding a system, but since that doesn't seem to be working you can try and add it to the host system's authorized_keys file first.

>  2. where the authorized_keys file is ? (local or remote) ?

It needs to be in the authorized_keys of the remote (the host it is trying to connect too)

```
cat id_rsa.pub | ssh USER@HOST "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
```

**Comment by pshanmu** [comment]
Hi

How do I reset admin password - I forgot it. (sorry i did not note it down)

- Shanmu

**Comment by skavanagh** [comment]
```
passwd root
```

**Comment by pshanmu** [comment]
Sorry to trouble for this basic work.

I forgot the admin password of KeyBox

How to reset the password ?

user: admin
password: root

not going !!

- Shanmu

**Comment by skavanagh** [comment]
The default password is 'changeme'.  If you forgot you can delete the jetty/keybox/WEB-INF/classes/keydb/keybox.h2.db file and restart the server to start over again.

**Comment by pshanmu** [comment]
Hi

finally done. password reset done as per your suggestion.

Following one worked


cat id_rsa.pub | ssh root@lb2.blr.cherrylabs.in "mkdir -p ~/.ssh && cat >>
~/.ssh/authorized_keys"


Not sure why it can not do it automatically (any issues related to freeBSD
!! :( )


Thanks for your wonderful support.


- Shanmu

**Comment by nox-do** [comment]
Anoyone interested in an optional config element like:

#resetAdminPassword=false

if exist we reset the password and set back the config entry to false.

Or is there any scurity concern?

Regards,
Daniel

**Comment by pshanmu** [comment]
Hi Kavanagh,

My sincere thanks for the tool and it makes the work so easy. In fact after
deploying and started using only i could see how beneficial it is.

Thanks again.

- Shanmu

**Comment by skavanagh** [comment]
@pshanmu - No problem at all!! Glad you like it.

**Comment by kramer2** [comment]
file keybox.h2.db is not exist. how to reset admin password ?

**Comment by abhinav193** [comment]
an Ubuntu aws instance does not have any password it consists of only key's, what password should we give while adding a system

**Comment by skavanagh** [comment]
You can take the public key for KeyBox under Settings and register it as an SSH key with AWS. That way you can use it when you create instances in the AWS console.  Otherwise, you’ll have to add the public key to the authorized keys file by hand.
