### ISSUE TITLE
Error: No such file

### ISSUE THREAD

**Issue by ausip** [skavanagh/KeyBox#80]
I am trying to login to systems via SSH from Keybox. I have one working and the rest are being problematic, yet I can't pinpoint the difference between them.

When creating a Composite SSH Terminal Session I am asked for the password which I enter correctly.
Keybox responds with an error "Error: No such file" followed by "No sessions could be created"

I can ssh from the console of my Keybox machine to the target SSH system using the same ssh username and password with no problems.

Looking at the /var/log/secure on the target system, I find the following lines after the login attempt.

May 27 13:25:09 www sshd[23555]: Accepted password for ausip from 10.110.110.30 port 44494 ssh2
May 27 13:25:10 www sshd[23555]: pam_unix(sshd:session): session opened for user ausip by (uid=0)
May 27 13:25:10 www sshd[23559]: subsystem request for sftp

Any ideas what i am doing wrong?

Thanks
Paul

**Comment by skavanagh** [comment]
It sets the 'authorized_keys' file when you connect, so maybe check your systems out.
Go under Manage -> Systems, then edit the one you are seeing the error with.  Take a look at the value for 'Authorized Keys' and make sure that file and path exists on the defined system for that user.  (It could be that there is no .ssh directory too)

**Comment by WRJFontenot** [comment]
You'll get that error if the .ssh directory doesn't exist in the login user's home directory.

Check to make sure you have a both an .ssh directory and the directory permissions are set to 700.  You also need to create a authorized_keys file and set the file permissions to 600.  The app will only create an authorized_keys file if the .ssh directory exists, but the current version won't set the correct permissions on the file.

The sshd process won't let you login using SSH keys if either the .ssh directory or authorized_keys file have the wrong permissions.

The fix your problem, login using another SSH client such as PuTTY and execute the following commands:

# mkdir .ssh
# touch .ssh/authorized_keys
# chmod 700 .ssh
# chmod 600 .ssh/authorized_keys

After doing this, you will be able to login using KeyBox and have it start managing SSH keys.

**Comment by ausip** [comment]
Go it sorted thanks @skavanagh & @WRJFontenot.
The .ssh directory did not exist in the users home folder. I have modified my initial VM creation procedure to include the following script commands

mkdir /home/"username"/.ssh
touch /home/"username"/.ssh/authorized_keys
chown "username":"username" -R /home/"username"/.ssh
chmod 700 /home/"username"/.ssh
chmod 600 /home/"username"/.ssh/authorized_keys

This way, if I have multiple users to give access via KeyBox, I can setup their authorized_keys file when I create the user in nix.
