### ISSUE TITLE
Add username@keyname as a comment to user generated public keys

### ISSUE THREAD

**Issue by WRJFontenot** [skavanagh/KeyBox#85]
When a user creates a new key, the comment section of the public key is blank, making it hard to know who owns that key:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCmUVoeraE31879V1Uc7IH0wlWB8Z0Sx8yAstmiV2a9GH1XdiRqHFBsFlqGaAY/CUovah8x2RuUbrP0PM7OxDX2YEOsHMoJevl11LTFvjPiQlw83Rp9qdD/vepEEDnDeaUT8K8s/UbZnRq7xK/rO2cVE0yjLrovFK+94BGFxzi79Q==
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCKF/XlA7dmXDKT/F0TUhtH9jvDXeg2nFTGI/gq+E5qJV8Vf7qM+pZk7st2hv2VS1UO3yO8AQLXXdJOiYcIMMUb9BfegxsZ6YcA5xtRzBkcWKJhirESQq/AsXmT04EUd7P51nzVmpsP/xyPyKuPDKwZKdfWtrLy3+Ju9jNmlePtZw== KeyBox generated key pair            

Adding "username@keyname" as a comment would make it easier to know who's keys are who's:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCmUVoeraE31879V1Uc7IH0wlWB8Z0Sx8yAstmiV2a9GH1XdiRqHFBsFlqGaAY/CUovah8x2RuUbrP0PM7OxDX2YEOsHMoJevl11LTFvjPiQlw83Rp9qdD/vepEEDnDeaUT8K8s/UbZnRq7xK/rO2cVE0yjLrovFK+94BGFxzi79Q== bsmith@MyNewKey
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCKF/XlA7dmXDKT/F0TUhtH9jvDXeg2nFTGI/gq+E5qJV8Vf7qM+pZk7st2hv2VS1UO3yO8AQLXXdJOiYcIMMUb9BfegxsZ6YcA5xtRzBkcWKJhirESQq/AsXmT04EUd7P51nzVmpsP/xyPyKuPDKwZKdfWtrLy3+Ju9jNmlePtZw== KeyBox generated key pair

**Comment by skavanagh** [comment]
:+1:
