### ISSUE TITLE
Copy/Past in a terminal

### ISSUE THREAD

**Issue by Barikad** [skavanagh/KeyBox#86]
Promising project.
Currently, we can copy from a terminal, but it is impossible to past to a terminal.
I'm not even sure this is technically possible. But it would be a useful feature.

**Comment by skavanagh** [comment]
Thanks!!  It's pretty tricky actually and I think I broke it when trying to fix selecting text from the terminal. It should work with CTRL-C, CTRL-V and from the menu now.
