### ISSUE TITLE
Users assignment in Profile section

### ISSUE THREAD

**Issue by colandre** [skavanagh/KeyBox#95]
It should be nice to have the way to assign users to a profile in profile edit page.
So an additional button "Assign Users" in profile page next to "Assign systems".

This will help users assignment in case of a new profile creation.

Thanks

**Comment by colandre** [comment]
Hello @skavanagh,

any news about this? It would be helpful to identify users allowed to use a certain profile.

Thanks

**Comment by skavanagh** [comment]
+1 should be pretty straightforward
