### ISSUE TITLE
Importing users SSH key

### ISSUE THREAD

**Issue by handycz** [skavanagh/KeyBox#98]
It would be nice to have an option to import users public key, when user has his own private/public key pair, so this key could be deployed. Now users have to keep two keys - one for machines managed by KeyBox and another one for machines that are not managed by KeyBox (unfortunately, I can't manage all machines by KeyBox).

**Comment by skavanagh** [comment]
If you set
'''
forceUserKeyGeneration=false
'''
In the KeyBoxConfig.properties it will allow them to just set the value of the public.

**Comment by handycz** [comment]
Thanks, but when using this option, users have to generate all keys externally. I think it should be possible to use both methods - generating new keys inside system and importing existing keys (without changing configuration and restarting).

**Comment by tvb** [comment]
`forceUserKeyGeneration=false` is what I was looking for all along!

**Comment by Pupp3tm4st3r** [comment]
Hey,

have to answer on this again respectively ask a question in relation to the topic:

I´ve set forceUserKeyGeneration=false but how does a user import his present ssh public key? Can´t find any button or mask...

**Comment by skavanagh** [comment]
so as an admin you add systems, add profiles, add users, assign users to profiles, assign systems to profiles, and then when the user logins in they can set their own public key.

**Comment by Pupp3tm4st3r** [comment]
Yeah I know. But funny thing was: When changing the forceuserkeygeneration the manage ssh field wasn´t available for user or administrator.

**Comment by skavanagh** [comment]
huh!.. make sure you have

`keyManagementEnabled=true`

set also!

**Comment by Pupp3tm4st3r** [comment]
But as in the comments:

set to false to disable key management. If false, the KeyBox public key will be appended to the authorized_keys file (instead of it being overwritten completely).

I don´t want to replace the authorized_keys file - append would be better...

**Comment by skavanagh** [comment]
Yeah.. that wording is confusing.. 

When you enable key management it's going to always overwrite that file b/c you want to prevent outside entries that haven't been registered.

if you allow users to slip in entries to the authorized_keys file on their own, it defeats the purpose of managing keys.

forceUserKeyGeneration is meaningless without keyManagementEnabled set to 'true'

Hope this helps.. (at least explain the reasoning)
