### ISSUE TITLE
Audit Storage

### ISSUE THREAD

**Issue by changwuf31** [skavanagh/KeyBox#99]
Where is the audit data stored ? 
Is it stored on the sqlite db?
Can we move it to mysql or postgresql ??

Thanks for this great app :+1:

**Comment by skavanagh** [comment]
It's actually in the H2 database (it's embedded much like sqlite).  That's
kind of why I have it marked as experimental, even though it gets a lot of
use.  A large datastore or maybe having the option to ship to a logging
server (just for the auditing data) would be great.  I like have the other
data embedded and would probably never want that going over the network (it
makes it better for security).

**Comment by changwuf31** [comment]
Ic, then i wonder if there is any easy way to change the embedded h2 db to mysql ?

**Comment by skavanagh** [comment]
Another option now is to set a log4j appender for audit storage 
See https://github.com/skavanagh/KeyBox/issues/19
